### PR TITLE
(#4073) - check pouchdb.min.js size < 50000

### PR DESCRIPTION
**Pull request by nolanlawson**

### CODE REVIEW

**Comment by daleharvey** [comment]
:+1: , though if you wanted to switch it to 200KB when you land I would be down for that, cheers I should have done this a while ago

**Comment by nolanlawson** [comment]
Yeah, 50KB is a bit strict, but I'd be fine with upping it as necessary. I'm hoping we can figure out some tricks to continue keeping it under 50.

**Comment by nolanlawson** [comment]
5a3602cf35d05f98326f5d88ebb8cbeabd5fa3b7

**Comment by daleharvey** [comment]
Ah I missed your were testing grip size, I thought it was 500KB and too high. My mistake

**Comment by nolanlawson** [comment]
Yeah I'm using `gzip -c pouchdb.min.js | wc -c` which is the min+gz size in bytes.

**Pull request closed without merging**
