### PR TITLE
fixes bug when using with pouchdb-async-storage

### PR DESCRIPTION
**Pull request by joshblour**
addresses https://github.com/nolanlawson/pouchdb-async-storage/issues/6

### CODE REVIEW

**Comment by nolanlawson** [comment]
Thanks! However, this seems to be a bug caused by subtle differences between webpack/browserify. So your PR is failing the tests because it breaks Browserify.

I suggest a better way to solve this: create our own `requestWrapper.js` that simply wraps request, then create a `requestWrapper-browser.js`. The reason I am guessing this will work is because it is the strategy we use everywhere else (see all the various `-browser.js` files), and it seems to be working for webpack users.

Maybe we should also start testing Webpack in Travis.

**Comment by joshblour** [comment]
Ok. I'd love to submit a pr with that fix but I'm still really new to all these components. Maybe once I get a bit more comfortable.




Also, not to hijack this thread, but the other issue is that even once I'm able to run it on react native, the promises never resolve. Any ideas what could be causing this?

**Comment by nolanlawson** [comment]
I'm not sure. Is that on iOS or Android? If you can try to debug, that would be helpful. Very few people are playing around with PouchDB+ReactNative in my experience. (Also please open a separate issue for that. :))

**Comment by nolanlawson** [comment]
Opening a new issue as #4700, thanks for the clues about what's going wrong here.

**Pull request closed without merging**
