### PR TITLE
Wraps anchors in divs to fix header appearance

### PR DESCRIPTION
**Pull request by dlakata**
Sorry about letting #5495 slip my mind. I've changed the solution to just wrap the anchors in a div.

### CODE REVIEW

**Comment by nolanlawson** [comment]
Thanks for picking this up again! I tried to do `npm run build-site`, but I'm getting:

```
 Error: Command failed: bundle exec jekyll build
  Liquid Exception: Liquid syntax error (line 143): Unknown tag 'endmarkdown' in adapters.md
```

Unfortunately this fails on `master` too so I'm really not sure what's going on. Probably some gem is out of date, but I tried `sudo gem install jekyll` and no dice. 😕

**Comment by nickcolley** [comment]
Thanks @dlakata !

We just need to make sure the extra whitespace doesn't cause any problems, we had some odd behaviour where markdown would not render unless everything in the partial was on one line 😱

**Comment by daleharvey** [comment]
@nolanlawson that was a mistake in our code, looks like changes to the validation have meant it shows up now, but pushed an r=me fix to master so should be fine now

@dlakata Thanks for the PR, I gave it a test but still seeing the `Using db.put()` on the same line unfortunately

**Comment by dlakata** [comment]
I'm having trouble getting ```npm run build-site``` to succeed, even on a clean clone of the repo. Any ideas what the issue might be?

**Comment by daleharvey** [comment]
What error are you seeing? did you do `npm run install-jekyll`? instructions are @ https://github.com/pouchdb/pouchdb/blob/master/CONTRIBUTING.md#building-pouchdb-documentation

**Comment by dlakata** [comment]
Whoops, forgot to mention the error. Yeah, I followed the instructions in the contributing doc and am getting the same thing as Nolan above:
```
Error: Command failed: bundle exec jekyll build
Liquid Exception: Liquid syntax error (line 143): Unknown tag 'endmarkdown' in adapters.md
```
What exactly was pushed to master to fix this error?

**Comment by daleharvey** [comment]
Ugh sorry, I had left the push in another tab without noticing it failed, repushed and should be fixed no - https://github.com/pouchdb/pouchdb/commit/d47c4535ae49d24bcf1dba3fdcdf9edd80499056

**Comment by dlakata** [comment]
I've merged master into this, so hopefully that fixes the build. Also, I'm seeing ```Using db.put()``` on its own line, as well as the other problematic headers. Perhaps check it out again now that ```npm run build-site``` isn't an issue?

**Comment by nolanlawson** [comment]
Tested locally, looks fixed to me! Thanks much for the PR. :heart:

**Pull request merged**
