### PR TITLE
(#3453) - Remove ie from allowed failures

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by daleharvey** [comment]
This is pretty green in https://travis-ci.org/pouchdb/pouchdb/builds/48252525

**Comment by daleharvey** [comment]
3/20 is around the rate we generally get from saucelabs, it isnt perfect but better than being an expected failure

**Comment by nolanlawson** [comment]
I'm used to seeing about 75% failure rate, so that is phenomenal

**Comment by daleharvey** [comment]
Surprisingly it was the db.destroy() commit that got this more stable

**Pull request closed without merging**
