### PR TITLE
(#6859) - Remove isPouchDbServer from tests

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by daleharvey** [comment]
Yup good catch cheers

**Comment by daleharvey** [comment]
@dharders wanna review this now? all green just needs a +1

**Comment by dharders** [comment]
+1, LGTM @daleharvey 

PS I assume the Istanbul ignores will be removed in a separate PR?

**Comment by daleharvey** [comment]
Cheers, yup its hard to keep track of the istanbul ignores, will likely have to do a sweep on all of those

**Comment by daleharvey** [comment]
And sorry I assumed you had been added as a committer and could +1 on the actual PR's, but I have invited you now, thanks :)

**Comment by dharders** [comment]
Yeah didn't have write access previously so assumed you just wanted eyes on

Thanks for the invitation though! Will make CI restarts easier now too ;)

**Pull request merged**
