### PR TITLE
Fix testrunners of couchdb v2 and add couchdb v3

### PR DESCRIPTION
**Pull request by julianhille**
Lets see if it builds.
If it does it fixes some build issues with COUCH_HOST

This would need another build to ensure tests against v3 (latest).
But for a couch v3 we need to wait for: https://github.com/pouchdb/pouchdb/pull/8069

Merged 8096 to see if this builds with v3

### CODE REVIEW

**Comment by julianhille** [comment]
Last build was succesfull besides one test having a timeout.
This tests now couchdb v3 and v2 successful

**Comment by julianhille** [comment]
@garethbowen this should fix all test failures, but it now failes with a `pouchdb.min.js` size failure and all the tests according to that file fail too. The size is "lower then 20" so this might be a caching issue.
My local builds do not have that issue, the personal biulds on travis had the same until "cache clear and rerun" maybe there is a similar issue here.

Please take a look if you can see something what might broke the `pouchdb.min.js` or clear cache and rerun those tests.

**Comment by julianhille** [comment]
@daleharvey may you reset caches and rebuild? This should fix all test fails.

**Comment by garethbowen** [comment]
Caches cleared and build restarted.

**Comment by julianhille** [comment]
rebased on master

**Comment by julianhille** [comment]
@garethbowen please restart again its running but one job was too slow on sauce labs ios.
this PR makes Travis green again.

**Comment by garethbowen** [comment]
Restarted.

**Comment by julianhille** [comment]
These sauce labs tests are really flaky. I'd say take a look and maybe merge cause it fixes Travis mostly.

**Comment by garethbowen** [comment]
Agreed - it's better than `master`. Merging.

**Comment by garethbowen** [comment]
Merged. Thanks!

**Pull request merged**
