### PR TITLE
(#4791) - add tests for filtered sync

### PR DESCRIPTION
**Pull request by nolanlawson**
I realized from #4791 that this was untested. The tests pass.

### CODE REVIEW

**Comment by daleharvey** [comment]
Looks like genuine failures

**Comment by nolanlawson** [comment]
There were failures at first due to not using `PouchDB.utils.Promise`, but I think it ought to be fixed now. If not, then it's a bug in our sync.

**Comment by nolanlawson** [comment]
Not sure if these are true failures or just strong intermittents.

**Comment by daleharvey** [comment]
Theres definitely an issue with the test, a bug with `paused` seems most likely, will take a look at this

**Comment by daleharvey** [comment]
Rerunning the tests just to get an idea if there are specific configurations failing

**Comment by daleharvey** [comment]
So I made a silly mistake when I looked at this last time, switching the test to check for change events instead of 'paused' ones should be fine, its going to be hard to ensure the guarantees for the paused event that this test depends on but the change events assertions are very much ones we need to guarantee

**Comment by nolanlawson** [comment]
:+1:

**Comment by nolanlawson** [comment]
48774ae428533a6dd1d6411c333bcebe296360b4 and 0a66a762c76c0b56c39c4911f6444034a6a3e28c

**Pull request closed without merging**
