### PR TITLE
(#3155) - Replace syncStopped / started with active / paused

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by daleharvey** [comment]
@nolanlawson How about this, I took out the explicit references to `retry` while its not enabled yet and tried to explain the events in terms of their semantics, first thing I will be doing this is fixing tests so we can get retry in

**Comment by daleharvey** [comment]
Also sorry, usually try to preserve extra commits but with us both editing the same small piece I just had to squash them

**Comment by nolanlawson** [comment]
No harm, no foul. The docs look good; I think the most important thing will be to add a new section to the guide with code samples.

**Comment by nolanlawson** [comment]
So yeah, +1. We've got a month to figure this out; I think the new `retry` stuff should be the focus for 3.3.0. :)

**Comment by daleharvey** [comment]
woot - https://github.com/pouchdb/pouchdb/commit/fb3a8e0e0621dadcc565bb5f47ca21dfd18fa04d

will work on retry now

**Pull request closed without merging**
