### PR TITLE
[wip] Generate views quicker the first time they're accessed

### PR DESCRIPTION
**Pull request by alxndrsn**

### CODE REVIEW

**Comment by daleharvey** [comment]
@alxndrsn Hey are you still working on this?

**Comment by alxndrsn** [comment]
@daleharvey not actively :(  Want me to close it?

**Comment by daleharvey** [comment]
Yeh if you arent working on it at the moment that would be great, the PR tab is like inbox 0 for me :) feel free to reopen when you are working on it / anything that needs tested

**Comment by alxndrsn** [comment]
👍 I wish I had more time - I think this could be a really good optimisation.

**Pull request closed without merging**
