### PR TITLE
(#4715) - simplify `npm run build`

### PR DESCRIPTION
**Pull request by nolanlawson**
Tried to break this PR up to isolate what's causing the failure.
This one is the big one that migrates from build.sh to build.js.

### CODE REVIEW

**Comment by nolanlawson** [comment]
Welp, this reproduces the failure.

**Comment by nolanlawson** [comment]
I don't have time today to look into this, but I found a minimum reproducible test case here: https://github.com/nolanlawson/repro-pouchdb-4741

**Comment by nolanlawson** [comment]
I filed the issue on npm (https://github.com/npm/npm/issues/11101) and managed to find a workaround by removing some unnecessary deps (specifically `duplexify`). Fingers crossed that this works...

**Comment by nolanlawson** [comment]
Green!

**Comment by daleharvey** [comment]
:+1: this looks great, sorry it was such a hassle. I have some issues but can address them in follow up issues - https://github.com/pouchdb/pouchdb/commit/d718a4dcafbcc9f76f4b9c27aab9d803472fe668

**Pull request closed without merging**
