### PR TITLE
(#3279) - 3.2.1 blog post

### PR DESCRIPTION
**Pull request by nolanlawson**
This blog post was written under the assumption that nothing more will be merged before 3.2.1. That's still debatable of course :)

### CODE REVIEW

**Comment by daleharvey** [comment]
+1, this is great, https://github.com/pouchdb/pouchdb/commit/3a3de46e93eda14289768e347b4e199d4cf6a3da got merged as well

I think the momumental amount of work @willholley has done on the couch-master tests is worth pointing out as well though

**Comment by nolanlawson** [comment]
updated!

**Comment by daleharvey** [comment]
Yup this is looking great, cheers

**Comment by nolanlawson** [comment]
6def07fad8f8b6935f9e587acfbd5f0c0de4d680

**Pull request closed without merging**
