### PR TITLE
fix double encoding database name in http adapter

### PR DESCRIPTION
**Pull request by lupomontero**
See https://github.com/pouchdb/pouchdb/issues/4314#issuecomment-155931616

### CODE REVIEW

**Comment by daleharvey** [comment]
This is great thanks, the code looks good, it definitely needs a test though, if you want to add a test that would be great, otherwise I will try to get to it, the test would be pretty much identical to 

https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.basics.js#L38

but with a url encoded name given

**Comment by daleharvey** [comment]
I added a test @ it, it failed before, passes with this fix, fairly certain we are good to go but will make sure its green then merge, thanks

**Comment by daleharvey** [comment]
Ok thats great, test is all green so merged, thanks so much - https://github.com/pouchdb/pouchdb/commit/ba4df1166d1554a0b26b9714d991ba534b297377

**Comment by lupomontero** [comment]
@daleharvey nice one! many thanks! (sorry for the slow reply)

**Pull request closed without merging**
