### PR TITLE
update docs with Chrome safe high Unicode character (#6456)

### PR DESCRIPTION
**Pull request by bmihelac**
Use '\ufff0' instead of '\uffff' which does not work in Chrome with http
adapter.

### CODE REVIEW

**Comment by willholley** [comment]
looks great - thanks for the  PR!

**Comment by willholley** [comment]
@bmihelac minor nit - can you reformat the commit message using the standard pattern for this repo: `(#6456) - update docs with Chrome safe high Unicode character`?

**Comment by bmihelac** [comment]
@willholley thanks for review and advice. I have updated commit message.

**Comment by willholley** [comment]
thanks @bmihelac - merged!

**Pull request merged**
