### PR TITLE
WIP - (#3898) - Make auto_compaction default to true

### PR DESCRIPTION
**Pull request by daleharvey**
Seeing what tests may fail

### CODE REVIEW

**Comment by nolanlawson** [comment]
I'm fairly -1 on changing the auto_compaction default to true. Many tests will break, yes, because there are a lot of tests to ensure that old revisions are still there, but also I think it would just be a confusing change for users, even in a major version. And plus, plugins like [pouchdb-full-sync](https://github.com/nolanlawson/pouchdb-full-sync) show the value of the "keep everything forever" feature.

If you want to see which tests will break, though, just grep the tests for `auto_compaction: false`, because I explicitly have to do that, given that we are now testing auto-compaction in CI. There are also special tests for `auto_compaction: true`.

**Comment by nolanlawson** [comment]
If you want to see which tests will break, though, just grep the tests for `auto_compaction: false`, because I explicitly have to do that, given that we are now testing auto-compaction in CI. There are also special tests for `auto_compaction: true`.

**Comment by nolanlawson** [comment]
I would actually hold off on merging this immediately, due not only to the failures but also because I have @boennemann's "fear of incrementing the major version": https://twitter.com/janl/status/598840861015801856.

So far, there is nothing in master that would force us to increment the major version. I would like to focus on stability for the next few releases (especially due to recent calamities that make me wonder about PouchDB's robustness). Then when things settle down, I'd be happy to change `auto_compaction`, remove `PouchDB.destroy()`, remove the `updated`, `created`, `deleted` events, and all the other stuff we want to deprecate. Maybe we can make a branch that contains all these breaking changes, and then merge it in when we feel it's time for a 4.0?

**Comment by daleharvey** [comment]
Ok, I want this to happen but lets leave it a short while so it doesnt overlap which possible important fixes

**Pull request closed without merging**
