### PR TITLE
(#3553) - clarify docs on destroy()

### PR DESCRIPTION
**Pull request by nolanlawson**

### CODE REVIEW

**Comment by nickcolley** [comment]
Need to make sure the html didn't break the markdown rendering again..

**Comment by nickcolley** [comment]
Looks fine! @nolanlawson for the guide improvement, couldn't we just change those snippets to use db.destroy?

**Comment by nolanlawson** [comment]
Personally I feel like it's more confusing when documentation deprecates something by just removing all mentions of it, as if it never existed. :/

**Comment by daleharvey** [comment]
I think the API docs are the source for information about deprecated functionality, I do think @nickcolley is right about this, having a guide tell you to use this function, then saying right afterward that it may go away is more confusing imo.

**Comment by nolanlawson** [comment]
OK, I'm outvoted. I'll close this and make the fix elsewhere, in https://github.com/pouchdb/pouchdb/pull/3577 and related PRs.

**Pull request closed without merging**
