### PR TITLE
add Slack link to website footer

### PR DESCRIPTION
**Pull request by beardicus**
Addresses #4212

I had to install a few extra gems not mentioned in CONTRIBUTING.md, so I updated that as well. Hopefully that's cool.

### CODE REVIEW

**Comment by nolanlawson** [comment]
Cool! Could you please update the `gem` instructions in the `CONTRIBUTING.md` please? It'd be very helpful for new contributors. :)

Also protip: you can add `[skip ci]` to this commit message to skip the Travis build; it's not really necessary, because this is just a documentation change, so we don't need to run the full test suite agian.

**Comment by beardicus** [comment]
>> I had to install a few extra gems not mentioned in CONTRIBUTING.md, so I updated that as well.

> Could you please update the `gem` instructions in the `CONTRIBUTING.md` please?

I think I did this on the first commit. Is there some other place I'm missing that I should update? I probably should've split the changes to each file into separate commits, sorry.

I added:

    $ gem install jekyll redcarpet pygments.rb

along with some other language.

**Comment by nolanlawson** [comment]
Awesome, I really appreciate the change to the docs! Most of us installed those gems long ago, so we forgot they were even necessary.

Gonna amend the commit to match our commit message format, but other than that looks great. Welcome to the committers club! :)

**Comment by nolanlawson** [comment]
031f7dbde487537723185e0733f58ef6292c47e6

**Pull request closed without merging**
