### PR TITLE
#5063 update sqlite plugin docs

### PR DESCRIPTION
**Pull request by schamp**

### CODE REVIEW

**Comment by schamp** [comment]
hm, looks like I need to clean up something wrt those old commits

**Comment by schamp** [comment]
that looks better.

**Comment by nolanlawson** [comment]
Thank you very much - this looks perfect. I'll just squash your commits on the way in and then we're good!

I'm also going to add `[skip ci]` to the commit message to avoid Travis tests; they're not necessary when it's only a documentation change. Thanks again!

**Comment by schamp** [comment]
Thanks, didn't know about the [skip ci] trick.

**Comment by nolanlawson** [comment]
I made some small edits to the formatting, but really appreciated the tone and wording of the changes. Thanks again!

8e50e326cb0ec8f51435ad0fbf36e1fb99905c27

**Pull request closed without merging**
