### PR TITLE
Simpler id that is less likely to break #4094

### PR DESCRIPTION
**Pull request by olafura**
I've tried to find something more unique in the headers but it's hard to find anything that a proxy will not mess with.

### CODE REVIEW

**Comment by olafura** [comment]
#4094

**Comment by nolanlawson** [comment]
Hm, it fails with `DASHBOARD_HOST is required`. Is this one of those things where only owners can get their PRs checked for code coverage? @zoepage did you have a workaround for this by any chance? Looking at [this code](https://github.com/hoodiehq/pouchdb-hoodie-sync/blob/7be8ce852e796c7d51e07ee81072b3f1407f07c6/.travis.yml#L22-L23) and it seems promising.

**Comment by zoepage** [comment]
@nolanlawson If you add the `GH_repo` and coveralls key to travis, it should check the repo by default with every PR you get in, independent from the ownership / rights. (If you invite me to coveralls and travis, I can take a look).

Running coveralls in `after_success ` helps us the build won't fail, because it doesn't have any influence on the build. So this is what you'd need :)

**Comment by daleharvey** [comment]
the `DASHBOARD_HOST` is our issue, we upload the coverage results to our host so we could build all that fancy graph stuff ourselves - https://github.com/pouchdb/pouchdb/blob/master/bin/run-coverage.js#L4

Can just stop calling + delete that file now, just call `COVERAGE=1 npm test`

**Comment by daleharvey** [comment]
@olafura Sorry for the side track

For this commit, it is important we dont change the way id's are generated for existing clients, if they are using the uuid now they should continue to do so otherwise peoples replications will all start from 0 (reminding myself we should add a test to ensure that nobody breaks that)

I think the best short term fix is a try/catch around the JSON.parse and remove the `if (err)` from here

**Comment by nolanlawson** [comment]
The Coveralls thing was a temporary bug in Coveralls itself. Should be fixed now.

I tend to agree with @daleharvey though that we need to maintain backwards compatibility. Else everybody who upgrades will have their replications start from scratch. Handling the error sounds like a good compromise.

**Comment by daleharvey** [comment]
Ill write up tests for this shortly

**Comment by daleharvey** [comment]
@olafura Hey, cheers for the patch, I came up with a pretty similiar solution but handles the backwards compatibility issues with session_id here - https://github.com/pouchdb/pouchdb/pull/4217, Apologies for not explaining it fully, will try to next time, hope you can get to in another contribution :)

**Comment by olafura** [comment]
@daleharvey Thanks for that, I'm sorry about not being available to respond. Been really busy planning my move to Canada this week so hopefully I can help you out in the future.

**Pull request closed without merging**
