### PR TITLE
(#4575) - Dont test for specific error message

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by daleharvey** [comment]
First fail I ran up against running tests against local 2.0, in previous cases where couch is returning different error details we have just made the test less specific

**Comment by daleharvey** [comment]
2nd failing test I found, on successful bulkDocs we ensure the order of the results, however couchdb master no longer does for others, I think its safer to pass through couch results than try sorting them ourselves so I think its best to remove the assertion

**Comment by daleharvey** [comment]
So last change fixed `test.retry` when it was ran standalone but not when I run the full suite which is quite worrying as it usually indicates that there is something leaking across tests

**Comment by daleharvey** [comment]
Ok still investigating why the paused events work differently however looking at the test I believe the fixed assertion is correct in that active and paused are supposed to fire at least twice. Locally the tests arent super stable but these changes get it to pass intermittently locally at least.

**Comment by nolanlawson** [comment]
These changes all look good to me. In general I'm suspicious of testing for error names; it rarely works across node/browser/couch/etc. :+1: from me.

**Comment by daleharvey** [comment]
Awesome thanks, merged in https://github.com/pouchdb/pouchdb/commit/90801c6ca892f9a3225d30304721f1e20c426a1c

**Pull request closed without merging**
