### PR TITLE
(#3961) - replication of many attachments

### PR DESCRIPTION
**Pull request by nolanlawson**
Still not reproducing the attachment loss bug. But at least we have another test.

### CODE REVIEW

**Comment by daleharvey** [comment]
As mentioned in the other thread, worried that this is green which means we arent seeing the case where the browser is killing concurrent requests, taking a look

**Comment by daleharvey** [comment]
So yeh, if we bump this up to 1000 it starts to fail, I also expect with additional latency and larger files it will be much more sensitive. I think we can expand this to include more and larger files until we see it fail then we have a good basis for the upcoming fixes

**Comment by nolanlawson** [comment]
OK sweet, glad to know we have a test for it. And yeah, I see where you're coming from now. Makes sense.

**Comment by nolanlawson** [comment]
@daleharvey Any reason not to fix this? Seems like a reasonable test and may catch something in the future, even as-is.

**Comment by daleharvey** [comment]
Yeh I was meaning to rebase this and merge once green :+1:

**Comment by nolanlawson** [comment]
rebased

**Comment by daleharvey** [comment]
Merged - https://github.com/pouchdb/pouchdb/commit/70998d157c056a345f00fa9776ca971dc4de9565

**Pull request closed without merging**
