### PR TITLE
(#2936) - Update to semi official couch master docker image

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by marten-de-vries** [comment]
I think you wanted to reference #6936 instead of #2936 in the commit message. Otherwise, this looks good to me although I personally can't keep track of the differences between ``apache/couchdb``, ``couchdb`` & ``klaemo/couchdb`` anymore. The Travis failure seems genuine.

**Comment by daleharvey** [comment]
So afaik apache/couchdb and couchdb are essentially the same, both based off the klaemo build thats being replaced

The failure is genuine though

**Comment by daleharvey** [comment]
ok so it seems like some `bookmark` value has started being added to mango results which the tests do not expect

**Comment by daleharvey** [comment]
Taking the previous 👍 for this now that its green

**Pull request merged**
