### PR TITLE
Fixing #3838 (updating request to latest)

### PR DESCRIPTION
**Pull request by mainakae**
Fixing proxy issues on node v0.12, result of using old version of request lib.

### CODE REVIEW

**Comment by daleharvey** [comment]
Hrm this is failing in travis which by default tests 0.10, we should at the very least be testing .12, whether we want to drop support for .10 is a different question though

**Comment by nolanlawson** [comment]
dropping 0.10 support should be a major version bump (surprised `request` didn't do that). Could be done with 4.0.0, but I suspect we would lose a lot of users because many of us are still stuck on 0.10 due to uncertainty especially with the node/io split.

Believe it or not, I myself am still mostly running 0.10, due to compatibility headaches that I don't want to deal with just yet.

**Comment by nolanlawson** [comment]
Level's solution was to (temporarily?) publish a `level-11` package with 0.11 support. We could maybe do a `pouchdb-12` branch.

**Comment by daleharvey** [comment]
Yeh locally I am still using 0.10 too and we should be cautious about dropping older version support, looking into at least having tests run across versions before we decide on anything

**Comment by mainakae** [comment]
Seems 0.12 has broken some things, yup.

Still have a machine with 0.10.33, and now I'm trying to run the test battery with the current version of Pouch. Running into some errors, I'll try to make sense of it, probably my fault, not configuring properly the test environment or something.

**Comment by daleharvey** [comment]
Ok should hopefully have multiple versions of nodejs testing working in https://github.com/pouchdb/pouchdb/pull/3844

**Comment by nolanlawson** [comment]
Seems the new version of request fails our node tests. I'm getting an error in the attachments test:

```
  1) test.attachments.js- local:http Many many attachments replicate:
     Something wrong with the request
```

**Comment by nolanlawson** [comment]
Apparently related to request and not Node 0.10 vs 0.12, because Travis shows the same error with 0.10: https://travis-ci.org/pouchdb/pouchdb/jobs/62392954

**Comment by nolanlawson** [comment]
This seems to be failing the tests. Please reopen if you're able to get it working; else I'm happy to stay stuck on an old version.

By way of precedent, I will note that we are still on an old version of LevelDB even, due to breaking changed in `leveldown`. I don't believe code rots if left out in the sun for too long, so I am happy to stay on an older version if it's passing the tests. :)

**Pull request closed without merging**
