### PR TITLE
Add support for a 'persistentIndexedDB' option when creating a PouchDB

### PR DESCRIPTION
**Pull request by scottmtp**
This option will enable persistent storage on Firefox only. See https://github.com/pouchdb/pouchdb/issues/4315.

### CODE REVIEW

**Comment by daleharvey** [comment]
Nice thanks a lot, this looks great. however to bikeshed on this api, I am thinking 

```
new PouchDB('name', {storage: 'permanent'}); 
```
with the code looking a little like
```
opts.storage = opts.storage || 'temporary';
var req = indexedDB.open(dbName, {version: ADAPTER_VERSION, storage: opts.storage});
```
Its flexible in case new types get added and a little cleaner imo, what do you think? I think `storage` would be enough for the key name but its possible we may want to specify its for indexeddb, if so I cant remember if we are snake case or camel case these days, @nolanlawson ?

**Comment by nolanlawson** [comment]
Snake case is more my cup of tea, because it matches the CouchDB options.

And yeah, I would definitely be down for a `storage` option on the IndexedDB adapter; it would also open us up to support things like `fakeIndexedDB` or `shimIndexedDB` if we really wanted to.

Out of curiosity, why did Moz create this separate IndexedDB API?

**Comment by daleharvey** [comment]
Mozilla devs are worried about content filling up indexedDB to the point where the device is out of space. The basic semantics are that `permanent` will cause an initial prompt, but is never evicted, and `temporary` will not cause a prompt, but will be evicted when the device storage limit is reached based on LRU

**Comment by scottmtp** [comment]
Good suggestion, we may as well allow the user to specify the 'storage' value we're giving Firefox.

Is this what you were thinking:
https://github.com/pouchdb/pouchdb/commit/3e4e42351b892331b994d898ab2e60529e00cff6

I think we still need the test for opts.storage so we know whether the second arg to open should be an integer or an object.

**Comment by daleharvey** [comment]
Actually you are right, I didnt consider that other idb implementations may not support the properties object, probably safer to only use it if its specified

**Comment by daleharvey** [comment]
I think this commit is good, just need to reformat it to not break the linter, we have an 80char limit on line length, Thanks :)

**Comment by daleharvey** [comment]
Awesome cheers, merged in https://github.com/pouchdb/pouchdb/commit/eeb6a242ac63f52b44606e956b5d3aec5750c331

**Comment by nickcolley** [comment]
Do we need to document this?

**Comment by CatchSandeepVaid** [comment]
I think we are talking about providing persistent indexeddb storage for firefox only (as Firefox has a non-standard API for specifying persistent storage when opening an IndexedDB) BUT
This link [https://demo.agektmr.com/storage/](url) says that even we can use indexeddb for unlimited storage. Cant we use this in pouchdb and  provide persistent (or unlimited storage) for chrome on android as well?

**Pull request closed without merging**
