### PR TITLE
dont call sync events too often (fixes #5479)

### LINKED ISSUE #5479: Calling db.sync().on() multiple times calls callback functions too often
Hello,

when listening multiple times for a sync event, the callback functions are called too often:

```
[insert one document]
// outputs a
this.db.sync(this.cfg.syncGatewayUrl, options)
      .on('change', () => console.debug('a'));

// outputs a, b, a, b
this.db.sync(this.cfg.syncGatewayUrl, options)
      .on('change', () => console.debug('a'));
      .on('change', () => console.debug('b'));


// outputs a, b, c, a, b, c, a, b, c
this.db.sync(this.cfg.syncGatewayUrl, options)
      .on('change', () => console.debug('a'));
      .on('change', () => console.debug('b'));
      .on('change', () => console.debug('c'));
```

(tested with pouchdb@5.4.5)

### PR DESCRIPTION
**Pull request by hermitdemschoenenleben**

### CODE REVIEW

**Comment by daleharvey** [comment]
@hermitdemschoenenleben this looks good, thanks a lot. However could you provide a failing test here please? https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.sync.js would be the correct place and if I remember this wasnt much of a hassle to reproduce, it was a matter of attaching multiple handlers and making sure they get called the correct number of times

**Comment by hermitdemschoenenleben** [comment]
I added a failing test

**Comment by daleharvey** [comment]
That test looks perfect, thanks. Its failing linting, you can test that with `npm run eslint` however I just fixed those up and ammended the commit. Doing a test run at https://github.com/pouchdb/pouchdb/pull/5830 and will 👍 if green, thanks :)

**Comment by daleharvey** [comment]
Awesome all green, merged in https://github.com/pouchdb/pouchdb/commit/24b0c62559b4a59e0305dbc55ce9d582abb4f441

Thanks so much :)

**Pull request closed without merging**
