### PR TITLE
(#6039) - fix ids included in bulkDocs() responses

### PR DESCRIPTION
**Pull request by nolanlawson**
~~This reverts commit 2553fd77bf341976f205a5e7ae8352775dee7409.~~ _already reverted, added a true fix to this PR_

I don't understand what's failing exactly, but I don't have time right now to look into it. I'd suggest we just merge because otherwise everything is failing.

### CODE REVIEW

**Comment by nolanlawson** [comment]
On second thought, I found a fix, so I'll just add a new commit here.

**Comment by nolanlawson** [comment]
OK, so there's a race condition where the array passed in to the adapter's `_bulkDocs` function destroys the underlying documents, so it's not safe to check `doc._id` _after_ calling `_bulkDocs`. The fix is to copy an array of `_id`s before calling `_bulkDocs`. I also added a new test to check that the `id`s are returned correctly.

**Comment by nolanlawson** [comment]
I think it's important to have master green, so I'm going to make an executive decision and merge https://github.com/pouchdb/pouchdb/pull/6062/commits/095a9a28f4d5f697a55e22714cc8741966ba32b6 to master without a +1. this PR will now be the fix to re-enable `id`s on `bulkDocs` responses.

**Comment by willholley** [comment]
eek! Thanks for sorting this out @nolanlawson

**Comment by nolanlawson** [comment]
@willholley No prob, with our tests as flakey as they are, it's unfortunately kinda easy for race conditions to slip through. 😅

**Pull request merged**
