### PR TITLE
(#2839) - Implement revs_limit

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by marten-de-vries** [comment]
LGTM, but take that with a grain of salt since the storage part of the code isn't my forte.

**Comment by daleharvey** [comment]
Nolan already gave this a +1 if it didnt change the existing default, so cheers good enough for me

**Comment by daleharvey** [comment]
Merged in https://github.com/pouchdb/pouchdb/commit/5832d03e2796b090ae2a844278577fe2d994d982

**Comment by marten-de-vries** [comment]
Ok, nice!

**Pull request closed without merging**
