### PR TITLE
(#4756) - Fix for being borked when in Cordova/PhoneGap iOS

### PR DESCRIPTION
**Pull request by trygve-lie**
See #4756

### CODE REVIEW

**Comment by daleharvey** [comment]
@trygve-lie As mentioned on irc, will verify this locally but in the meantime there are jshint errors, you can check them with `npm run jshint`, looks like its just removing the jshint and import of cordova

**Comment by trygve-lie** [comment]
Sorry about that. I'll fix

**Comment by trygve-lie** [comment]
@daleharvey Any idea what is failing here?

**Comment by daleharvey** [comment]
@trygve-lie apologies, our tests arent 100% stable, this was just an intermittent, restarted and it passed, all looks good, doing some local testing right now

**Comment by daleharvey** [comment]
So it would be really great to have cordova in ci just to verify these changes, but without that will have to live with manual testing, this fixes a fatal bug for @trygve-lie and my local testing looks like everything is running fine.

From the code side of things, this was added to fix a race condition when starting up, I believe this was the same time we were implementing and seeing a lot of bugs with taskqueue (this code is pretty old). It really shouldnt be needed so happy to merge, thanks so much @trygve-lie

**Comment by trygve-lie** [comment]
@daleharvey Thanks for merging.

I have been thinking a bit on how to run automated tests on iOS and Android devices in general. This is very early in my thought process so just throwing out an idea here.

What if one make a simple phonegap app that just executes the test. Then we use the node client for phonegap build to build the iOS and Android app and when they are built execute them is an environment (docker?) which then finally runs the tests. Not super optimal but an idea.

**Comment by daleharvey** [comment]
We actually have most of that functionality in the tree - https://github.com/pouchdb/pouchdb/blob/master/TESTING.md#cordova-tests @nolanlawson wrote it while testing on various devices. I have been using it to test locally and although the command seems to have regressed (it exits early) the rest looks to still work.

It was a fairly huge amount of hassle to get it running on CI last time Nolan tried if I remember, but definitely something we would love to get working

**Comment by daleharvey** [comment]
However if we can get a docker environment that we can just send an app and it will run the tests for us, that seems like it could be easier, we setup docker for getting couchdb master testing and its working out pretty handy for pouch

**Pull request closed without merging**
