### PR TITLE
(#3446) - Add pouchdb-server + firefox to expected fails

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by daleharvey** [comment]
So I dont particularly want to do this, usually test failures should be backed out, however this isnt actually failing tests, they pass however the connection with selenium is lost, also the delete patch may have fixed the ie tests, so we might be able to get ie out of expected failures, which is more important

**Comment by daleharvey** [comment]
But looking into this, I want to get the rest of the expected failure out of there and in the green list

**Comment by nolanlawson** [comment]
So I take it this is happening because `new PouchDB().destroy()` is slower than `PouchDB.destroy()`? (Due to the implicit create-then-delete?) Kinda sad then to do this then; I would almost prefer to just roll back the `PouchDB.destroy` changes entirely. TBH I don't think anybody is using `destroy` (either variant) except for us, so messing with this seems to be causing more problems than it's solving.

**Comment by daleharvey** [comment]
I dont know what is causing it, I dont think its because it is slower in particular but when we do actually remove `pouchdb.destroy` we can vastly improve both its complexity and its performance, right now its going through a whole bunch of indirection so I would like to figure out why this is going wrong without backing it out

**Comment by nolanlawson** [comment]
OK, fair enough, let's move forward. +1 when green

**Comment by daleharvey** [comment]
Merged in https://github.com/pouchdb/pouchdb/commit/31b0821453744d41423a74ba5b86df7fdb219328

**Pull request closed without merging**
