### PR TITLE
(#7391) - Restore default of sending credentials with fetch requests

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by steodor** [comment]
If you're using `pouchdb-authentication` and the upgrade to `pouchdb@7.0.0` broke your login, this PR fixes it!

**Comment by daleharvey** [comment]
Will take that as a 👍 thanks :)

**Comment by barbalex** [comment]
Has this made it into pouchdb-browser v7.0.0? I have this exact same problem using that. And I can't use full pouchdb because that causes errors in gatsby v2.

Looks likle pouchdb-browser has not been updated in 4 months. Please update. Otherwise I am completely blocked.

**Comment by barbalex** [comment]
My problem is: I am not building the pouches myself. It is [rxdb](https://github.com/pubkey/rxdb) that does that. So I can not even apply https://github.com/pouchdb-community/pouchdb-authentication/issues/239#issuecomment-410489376 to circumvent the problem.

**Comment by barbalex** [comment]
please publish a new version

**Pull request merged**
