### PR TITLE
upgrade derequire

### PR DESCRIPTION
**Pull request by calvinmetcalf**

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
its ~60 times faster

**Comment by nickcolley** [comment]
At runtime?

**Comment by nolanlawson** [comment]
tried this out recently in another project, can confirm way faster

**Comment by nolanlawson** [comment]
BTW I was joking on Twitter about how you should increment the major version for every performance improvement. Hope that's not why you incremented it. ;)

**Comment by calvinmetcalf** [comment]
haha no since it switches from esprima to acorn code that it could previously parse it could theoretically error on.

**Pull request merged**
