### PR TITLE
fix: upgrade leveldown from 5.6.0 to 6.1.1

### PR DESCRIPTION
**Pull request by vapormusic**
Fix PouchDB not working on arm64 Apple Silicon machines (#8416)

### CODE REVIEW

**Comment by cyphercider** [comment]
I had the same issue, I can confirm upgrading leveldown to 6.x solved the problem

**Comment by garethbowen** [comment]
@vapormusic If you have a moment, can you have a look at the failing test?

**Comment by taratatach** [comment]
Hi. Are there any updates on this subject? Not being able to build applications using PouchDB on M1 processors is starting to be limiting :/.

**Comment by garethbowen** [comment]
@taratatach You can help by trying to get all the tests to pass. You may need to fork to your own repo to get the tests to run again.

**Comment by srl295** [comment]
anything new here?

**Comment by garethbowen** [comment]
Done via https://github.com/pouchdb/pouchdb/pull/8845

**Pull request closed without merging**
