### PR TITLE
(#4278) - Remove use of 'crazy' in documentation and tests

### PR DESCRIPTION
**Pull request by Charlotteis**
Seems alexjs isn't as robust as I would like it to be (it skips a lot of files) so I found these with a manual lookup in my files.

:sunny:

### CODE REVIEW

**Comment by nolanlawson** [comment]
Wow, surprised how often I use the word "crazy." +1

**Comment by nolanlawson** [comment]
So this is unfortunately failing because of some changes to the mapreduce tests; I was testing the sorting of various strings, so `strange` does not serve as a substitute for `crazy` because it sorts differently. :)

>  AssertionError: expected 'multiple values!' to equal 'strange!'

Since these strings can be anything, how about `crayon` or something that will sort the same but without the offensive connotations?

**Comment by Charlotteis** [comment]
Weirdly the tests passed for me when I did `npm test`, unless this is something different.
Will update in the morning :)

**Comment by daleharvey** [comment]
The map reduce tests are seperate from the integration tests, needs to be `TYPE=mapreduce npm test` for them

**Comment by Charlotteis** [comment]
@nolanlawson @daleharvey thanks for the help! Have run the mapreduce tests and all seems fine :)

**Comment by nolanlawson** [comment]
Cool, thanks!

**Comment by nolanlawson** [comment]
1e93a0df050171ae80fc067ffc8fa896f3641af4

**Pull request closed without merging**
