### PR TITLE
#7019 - Crash after have empty response in some xhr request in pouchDB

### PR DESCRIPTION
**Pull request by artemmorozov7**
#7019 - Crash after have empty response in some xhr request in pouchDB

### CODE REVIEW

**Comment by daleharvey** [comment]
Great thanks 👍

**Comment by artemmorozov7** [comment]
Thanks for the quick response. Could you tell me when the next release will be where will these changes come in?

**Comment by daleharvey** [comment]
We will be doing a release shortly, can follow along at https://github.com/pouchdb/pouchdb/issues/6999

**Comment by artemmorozov7** [comment]
Thanks

**Pull request merged**
