### PR TITLE
(#3112) - Docs i18n

### PR DESCRIPTION
**Pull request by nickcolley**
Ok got something working here.

Also needs the following:
- [ ] Nice language selector
- [ ] Contribution README doc update
- [ ] At least one page translated.

Think if we can get one page translated and make sure the site is working good with just that one we can gradually do the rest later?

### CODE REVIEW

**Comment by daleharvey** [comment]
> Think if we can get one page translated and make sure the site is working good with just that one we can gradually do the rest later?

I think ideally we can put up 2 pages, maybe like the home page in french and spanish using a google translate version for testing purposes, then invite people to come along and start contributing proper translations.

I would really like to see how to fallback, so if a translated page isnt available, maybe it shows the english with a link to a google translate?

This is an amazing change, cheers for picking it up :)

**Comment by nickcolley** [comment]
With this plugin if there's no translation it just shows the english content.

**Comment by nickcolley** [comment]
@daleharvey @nolanlawson do you think I could (or someone else) put a tweet out to see if anyone would be up for doing some translation?

**Comment by nolanlawson** [comment]
I have to admit that I have my reservations about this PR.

Having documentation in multiple languages is a worthy goal, but I don't think PouchDB has the resources to do this right now, and if we try to start down this path, then we will likely bite off more than we can chew.

Imagine when we change something and then need to go back and fix the docs. Is the committer going to fix the docs in Spanish, French, and German as well as English? No, what'll happen instead is that the foreign-language docs will rot and speakers of those languages will just go to the English version because they can trust it.

I'm all for inclusion, and as a fluent speaker of French who has worked in multilingual environments, I understand the pain that non-native English speakers have to go through just to participate in the global programming community. But I don't think we at PouchDB are in a reasonable position to help solve this.

**Comment by daleharvey** [comment]
Alternatively people contributing to translations is one of the most popular ways to get started within a project, I know for Mozilla our translation community is huge and we are still seeing a bunch of non english activity - http://frontinbrazil.com.br/pouchdb/, https://vpease.wordpress.com/2015/08/11/ionic-framework-pouchdb-y-cloudant-la-combinacion-perfecta-totalmente-expuesta/ etc

We will never require maintainers or contributors to fix things across all languages, but I think providing the option for people to do so would be awesome.

I do think the example @nolanlawson brings up is important to think about though, we would really need a mechanism for determining what translations are out of date and what changed. I think ideally we would want to show a warning on pages that have out of date translations but at the least someone translating locally needs a simple way to figure out what translations needed to do.

I think we should figure that out before asking people to start to contribute translations

**Comment by marten-de-vries** [comment]
Having something gettext-like would fix it: there wouldn't be multiple pages: just an English one in which all pieces of text that would need to be translatable are marked in some way. The translations would then be in separate (.po) files, and would only replace the English text if the piece of text didn't change in the meantime. If it really used gettext (.po) files, an additional benefit would be that we could use a dedicated translation site, making understanding git not a requirement for contributing.

The problem is implementing it. I haven't seen a ready made solution for jekyll yet.

**Comment by marten-de-vries** [comment]
As for implementation, I have suggested a node preprocessor for jekyll before: https://gist.github.com/marten-de-vries/d734b71fde92617e717c

A preprocessor because I don't know Ruby, regardless of language this does explain the concept in code though.

**Comment by nolanlawson** [comment]
Yeah, as I've said, I think this is more of a social problem than a technical problem for us. Mozilla might have the resources to do wide-scale translation, but we're small-time, so I don't think we do. :/

Also to Dale's point, I think the needs of foreign-language speakers is largely being served by the kind of blogposts he cites. I imagine there is a correlation between 1) people with low English comprehension, and 2) people who rely more on tutorials/blogposts/videos than official docs. Which indicates to me that translating the official docs would not be very high-value (although maybe the guide is an exception).

That said, if we do push forward on this, I could try my hand at translating the guide to French. :) I'd need a native-language speaker to go through and proofread, though. (My French is correct but lacks pizzazz.)

**Comment by zoepage** [comment]
> Alternatively people contributing to translations is one of the most popular ways to get started within a project...
100% yes on that.

It's always nice to announce one person per language to at least check if the documentation is up to date. No need they have to take care of it anytime. Just make clear if they don't have the time, they need help and get the word out.

A warning on the page is a good idea. Also providing a diff, if the main resource (here I'd suggest the english version of the docs) changes, so people who translate the docs in their language know what to change without a huge hassle.

This is how we do it with hoodie:
https://github.com/hoodiehq/documentation#translations

// folder structure
We have one folder per language. This is double content and not the best practice, but we figured the most simple solution for people to contribute to translations.

**Comment by nickcolley** [comment]
So looks like we need to decide a good way to automatically show a message for:
- A page that is in English because there's no translation, and how to contribute
- A page that is translated but out of date, how to contribute and where to find the original.

**Comment by daleharvey** [comment]
So I think this is awesome, the branch will be around however closing out PR's that arent active at the moment. People will still be able to find it when looking from the issue

**Pull request closed without merging**
