### PR TITLE
ci: use node 14

### PR DESCRIPTION
**Pull request by alxndrsn**
node 12 is EOL: https://nodejs.dev/en/about/releases/

### CODE REVIEW

**Comment by alxndrsn** [comment]
A couple of tests needed to be re-run in my fork's Actions, and one failed on pouch's Actions.  Is this normal?

**Comment by garethbowen** [comment]
@alxndrsn It's not uncommon.

**Comment by garethbowen** [comment]
@alxndrsn Definitely an improvement. Is it worth jumping to Node 18? What about using the Actions matrix to test a range of Node versions?

**Comment by alxndrsn** [comment]
> Is it worth jumping to Node 18?

Tempting.  I haven't tried it, but potentially more incidental updates would be required for dependencies.

> What about using the Actions matrix to test a range of Node versions?

I think that would be very helpful.  Currently I'm not sure the impact of the current line, which looks like it ignores the matrix version of node:

https://github.com/pouchdb/pouchdb/blob/55c2743e4b17a85b21f4f888ff8f02a2b31beaaa/.github/workflows/ci.yml#L17

**Comment by garethbowen** [comment]
It seems like some steps use `${{ env.NODE_VERSION }}` and some use `${{ matrix.node }}`. I think it would be less confusing to have all use `matrix.node`. It would be good to have multiple node versions in the matrix but there's already 60 builds so I'm reluctant to add too many more. Node 14 is fine for now...

**Review by garethbowen — APPROVED** [review]

**Comment by janl** [comment]
this looks great, thanks! We are about to do the 8.0.0 release and since this doesn’t affect the actual code, we’re holding this PR until after the release, hope that’s ok!

**Pull request merged**
