### PR TITLE
(#6736) - fix {binary: true} in db.get() with open_revs and HTTP adapter.

### PR DESCRIPTION
**Pull request by jerem**

### CODE REVIEW

**Comment by daleharvey** [comment]
Closing and reopening to see if I can kick travis off

**Comment by daleharvey** [comment]
Ooops sorry, tests failures are genuine here

**Comment by jerem** [comment]
Closed/reopened the PR to trigger CI.

**Comment by jerem** [comment]
Looks like tests are failing because of timeouts (just like master). Re-triggering CI once again.

**Comment by jerem** [comment]
🎉🎉🎉

**Comment by jerem** [comment]
@daleharvey tests are now passing. Ca you proceed with the review and merge? Thanks.

**Pull request merged**
