### PR TITLE
8225 Remove assigning content type to blob

### PR DESCRIPTION
**Pull request by saschwarz**
Attempt at resolving issue in #8225

### CODE REVIEW

**Review by daleharvey — CHANGES_REQUESTED** [review]
Hi @saschwarz 

Cheers for the patch, I am not sure why there are so many changes to the imports? In this bug we only need the last 3 lines of that diff that assign the `blob.type`, its very likely there will be test failures that come along with that but if you just push that change you can see where CI fails, right now the import changes are causing undefined errors

**Comment by saschwarz** [comment]
Sorry, I'm using prettier in my editor and it reorders imports - I didn't notice because I'm not seeing any import errors when I run my app.

**Review by daleharvey — CHANGES_REQUESTED** [review]
This is failing with @ https://travis-ci.com/github/pouchdb/pouchdb/jobs/470263668 with:

```
/home/travis/build/pouchdb/pouchdb/packages/node_modules/pouchdb-adapter-http/src/index.js

  616:9  error  'contentType' is assigned a value but never used  no-unused-vars
```

So that will need fixed

**Review by daleharvey — CHANGES_REQUESTED** [review]
Thanks for the prompt update, however this is still failing tests, likely there are tests that check that the content-type was assigned. Please run the tests and ensure they are passing before requesting review. Feel free to ping me if you have questions though. Thanks

**Comment by saschwarz** [comment]
@daleharvey I looked at the first few of the failing tests and don't understand why they are failing or how to fix them.

**Comment by daleharvey** [comment]
ok will close out then

**Comment by saschwarz** [comment]
@daleharvey I hoped you might be able to assist me with how to fix the failing tests. If you could give me some guidance I would try to get them to pass. I'm no longer using pouchdb but would like to help the project.

**Comment by daleharvey** [comment]
@saschwarz If you have specific questions, "I cant get this to work, I tried doing X and Y", or "I have trouble figuring out what is supposed to happen here" then I can try to help out best I can

**Pull request closed without merging**
