### PR TITLE
(#4410) - attempt 1 to upgrade firefox

### PR DESCRIPTION
**Pull request by nolanlawson**
don't merge, this is just for testing

### CODE REVIEW

**Comment by nolanlawson** [comment]
check the user agent to see if this is working

**Comment by daleharvey** [comment]
If you expand the "Build system information" at the top you get some more info
```
Installed Firefox version

firefox 31.0esr
```

**Comment by daleharvey** [comment]
So actually there is a bit below that, an `install_firefox` step which shows 41 being installed fine, the issue is that selenium isnt picking it up

**Comment by nolanlawson** [comment]
Weird - it turned out to be the selenium version. 2.45 works; 2.46 doesn't. Specifying the firefox version in `firefox:selenium:41` also works.

**Comment by nolanlawson** [comment]
OK, I figured out something that works. I'll just apply it to the #4403 PR.

**Pull request closed without merging**
