### PR TITLE
(#4049) - Stateless constructor for http adapter

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by daleharvey** [comment]
Some how managed to get the constructor in some type of infinite loop, but this should mostly be how it can work

**Comment by daleharvey** [comment]
So this mostly looks to be working, one small problem where I am likely doing something dumb

@nolanlawson it seems like your area of expertise, https://github.com/pouchdb/pouchdb/blob/4049/lib/adapters/http/index.js#L176 if the promise is in progress or fulfilled, I want to return it, if it is rejected then I want to try again, `setupPromise` never seems to get set to false like it should do https://github.com/pouchdb/pouchdb/blob/4049/lib/adapters/http/index.js#L228 though

**Comment by nolanlawson** [comment]
Chrome Canary has a dev tools experiment where you can see a list of resolved and unresolved Promises. I'll try that out and give it a go.

**Comment by daleharvey** [comment]
Ok woot, I think this is all good for review aside from pouchdb-server seems to be failing in the same way again

**Comment by daleharvey** [comment]
And to explain, the old test for 'retry working offline', was that in the test `var db = new PouchDB` happened successfully before we started failing requests, but if you do var db = new PouchDB('http://url') while offline that construction would fail and it would be impossible to pass it to the replicator.

This changes it so `var db = new PouchDB` returns immediately without doing any setup on the server, it can never fail, when you start doing requests against that db it then does the setup, if we start if offline + retry, the subsequent requests will retry the full db setup until you are online and it succeeds

**Comment by nolanlawson** [comment]
This causes a breakage in pouchdb-server, but everything else looks great. I'll file the pouchdb-server problem as a separate issue.

**Comment by nolanlawson** [comment]
f8c06ac76d321e84bdcab25f9cf02f5d648e06af

**Pull request closed without merging**
