### PR TITLE
feat: support partial_filter_selector

### PR DESCRIPTION
**Pull request by garbados**
This PR closes https://github.com/pouchdb/pouchdb/issues/8276 by modifying the abstract mapper used by pouchdb-find so that it will apply a partial_filter_selector at index time if one is present.

- [x] Includes tests.
- [x] Updates documentation.

### CODE REVIEW

**Review by daleharvey — CHANGES_REQUESTED** [review]
This looks great, cheers for the tests + doc updates, codewise it looks nice and simple too.

The failures arent looking obscure, definitely related to this PR so will need them fixed before merging - https://travis-ci.com/github/pouchdb/pouchdb/jobs/488719479

**Comment by garbados** [comment]
I feel a bit nervous about the copy+pasting done here but I didn't want to dip my toes into modifying the structure much. Hope that's ok!

**Comment by garbados** [comment]
Looks like more test failures. I'll keep at it :+1:

**Comment by garbados** [comment]
The remaining test failure doesn't appear related:

image

Let me know if there's anything else I can do to make this ready for merging.

**Comment by dheimoz** [comment]
Hello @daleharvey , hope you are doing great. It would be greatly helpful if you can take a look into this.

Thanks.

**Comment by garbados** [comment]
Hey, on the assumption that these test failures totally are my bad, I've been pushing little commits to try and make the difference. I can't reproduce these failures so testing like this is the only option I can think of.

**Comment by paultranvan** [comment]
@garbados Thanks for this PR, this is something that will be very useful to us at Cozy, to fix performances issues on some queries ! :+1: 
I assume the PR is blocked as long as the tests will fail? Do you think you will find some time to fix them? Thanks!

**Comment by garbados** [comment]
> @garbados Thanks for this PR, this is something that will be very useful to us at Cozy, to fix performances issues on some queries ! 
> I assume the PR is blocked as long as the tests will fail? Do you think you will find some time to fix them? Thanks!

I am out of threads to pull on debugging this issue. I'd really appreciate some senior expertise to point me in the right direction. I also really want to get these changes merged as it is a crucial feature of Mango.

**Comment by garbados** [comment]
OK, now I get different failures, which I am able to reproduce locally. Further commits coming soon...

**Comment by jbriales** [comment]
Hi there! I'm very interested on this as well, but unfortunately have no expertise on PouchDB side, but only pure beginner with it.
@garbados what's the current status for this? Still blocked by expert help coming? Or is there any basic work to get done where you could use extra help to get this finished?

**Comment by garbados** [comment]
@jbriales Hey, I'm still working on this. I haven't had the time to see it through yet, but I'm not blocked except by myself.

**Comment by garbados** [comment]
The issue was my assertion was overeager. It was missing some properties automatically assigned to Mango query results, such as bookmark. This has been fixed.

**Comment by garbados** [comment]
TESTS PASS!

**Review by daleharvey — APPROVED** [review]
This is great, thanks so much

**Comment by daleharvey** [comment]
🎉🎉🎉

**Comment by dheimoz** [comment]
thanks @daleharvey and kudos to @garbados !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by juanreynolds** [comment]
Hi, I'm not getting a correct result. I can see the index has been created but the result still includes documents that should have been skipped by the partial filter:

```
interface IDoc {
    _id: string,
    _rev?: string,
    index_field: string,
    partial_filter: 'a' | 'b',
}

const log = (title: string, data: any) => {

    console.log(title, JSON.stringify(data, null, 4));

}

const run = async () => {

    let pouch = new DbPouch('db_01') as IDbPouch;

    const res = await pouch.createIndex({
        index: {            
            ddoc: 'queries',
            name: 'idx_test',
            fields: ['index_field'],
            partial_filter_selector: { 'partial_filter': 'a' },
        }
    });

    log('createIndex', res);

    const resx = await pouch.get('_design/queries');

    log('view index', resx);

    const res2 = await pouch.bulkDocs<IDoc>([
        {
            _id: '1',
            index_field: 'abc',
            partial_filter: 'a'
        },
        {
            _id: '2',
            index_field: 'abc',
            partial_filter: 'b'
        }
    ]);

    const res3 = await pouch.find(
        {
            use_index: ['_design/queries', 'idx_test'],
            selector: { 'index_field': 'abc' }
        }
    );

    log('find', res3);

    pouch.close();

}

run().then(res => console.log(res)).catch(e => console.log('ERROR:', e))
```
OUTPUT:
```
createIndex {
    "id": "_design/queries",
    "name": "idx_test",
    "result": "created"
}

view index {
    "language": "query",
    "views": {
        "idx_test": {
            "map": {
                "fields": {
                    "index_field": "asc"
                }
            },
            "reduce": "_count",
            "options": {
                "def": {
                    "fields": [
                        "index_field"
                    ],
                    "partial_filter_selector": {
                        "partial_filter": "post"
                    }
                }
            }
        }
    },
    "_id": "_design/queries",
    "_rev": "1-63cc02e019ebbb82f52ca97c389fe5a1"
}

find {
    "docs": [
        {
            "index_field": "abc",
            "partial_filter": "a",
            "_id": "1",
            "_rev": "1-760b4f5c074bebfc1c98153e22d8bc43"
        },
        {
            "index_field": "abc",
            "partial_filter": "b",
            "_id": "2",
            "_rev": "1-40a61bc3202afdd553ef1d03eb2f282a"
        }
    ]
}

```

**Comment by garbados** [comment]
Uh oh! Lemme open up an issue to track this bug. D:

**Comment by Terreii** [comment]
> Uh oh! Lemme open up an issue to track this bug. D:

There is already a bug (#8522) and a fix #8523 for it.

**Pull request merged**
