### PR TITLE
(#3461) - Remove passing tests from allowed failures

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by daleharvey** [comment]
Try runs, 
couchdb-master @ https://travis-ci.org/pouchdb/pouchdb/builds/48265442
ie @ https://travis-ci.org/pouchdb/pouchdb/builds/48252525
pouchdb-server @ https://travis-ci.org/pouchdb/pouchdb/builds/48265213

All of them are mostly passing (I didnt do any restarts) highest was 3/20 failures and thats about as high as we get on saucelabs

**Comment by nolanlawson** [comment]
fantastic, let's do it!

**Comment by nolanlawson** [comment]
...when green of course :)

**Comment by daleharvey** [comment]
All green - https://github.com/pouchdb/pouchdb/commit/a46601208372b5bbab95b8c5a19984b3f7f71775

2 failing tests in couchdb-master and that nasty iphone bug to go

**Pull request closed without merging**
