### PR TITLE
#3608 Blog post, filtered replication

### PR DESCRIPTION
**Pull request by sphaso**
Just a couple of paragraphs on what I whish I knew before I got into the Couch+Pouch filtered replication game

### CODE REVIEW

**Comment by nickcolley** [comment]
Make sure to add yourself to https://github.com/pouchdb/pouchdb/blob/master/docs/_data/authors.yml as it's used to generate the blog etc :)

**Comment by sphaso** [comment]
Added! thanks for the heads up :)

**Comment by nolanlawson** [comment]
@sphaso Could you please create a Gravatar? I'm just seeing the default Gravatar icon at https://gravatar.com/avatar/7e7d121f555821c5f191ba484f9b2aca

**Comment by sphaso** [comment]
Must have been a copypasta mistake. Now it should be the correct hash :)

**Comment by nolanlawson** [comment]
I'm working on adding some small copyedits, but I hope to publish this post with 3.3.0. Looking very good. :)

**Comment by nolanlawson** [comment]
Some quick tips:

* this was failing `npm run build-site` because you need to escape the colon in the title for Jekyll
* we use two spaces in our code samples
* I assume `bolla` is Italian for `foobar`? :) In French they say "toto" and in Danish "bongo".
* I plan on releasing your post with 3.3.0, so no need for a warning about using master.

I'm going to create a PR with my suggested fixes and copyedits.

**Comment by daleharvey** [comment]
Merged in https://github.com/pouchdb/pouchdb/commit/aeac031151c3f957c38da95aa6b719c445d33db2

**Pull request closed without merging**
