### PR TITLE
Document pouchdb-collate on pouchdb.com

### LINKED ISSUE #6299: Document pouchdb-collate on pouchdb.com
Currently the documentation for this module only lives at http://github.com/pouchdb/collate . But since that repo has been moved over here, it should be documented on pouchdb.com instead.

### PR DESCRIPTION
**Pull request by letsila**
Fixes #6299

### CODE REVIEW

**Comment by daleharvey** [comment]
This is great work thanks however as collate isnt part of the core API it should not be on this page. Having a page linked from https://pouchdb.com/external.html would be fine, I cant see a more appropriate place for it at the moment, although honestly I think linking to https://github.com/pouchdb/pouchdb/tree/master/packages/node_modules/pouchdb-collate from the plugins page would be most appropriate here (apologies since that wasnt what the bug suggested)

**Comment by letsila** [comment]
Actually I was not really sure where to put it.

**Comment by letsila** [comment]
Ok I'm gonna move it to the plugins page.

**Comment by letsila** [comment]
Do the plugins listed on the plugin page follow any kind of ordering rule or it's ok to put the link anywhere I want?

**Comment by daleharvey** [comment]
We try for alphabetical

**Pull request merged**
