### PR TITLE
(#8581) -  Fix this of changesHandler

### PR DESCRIPTION
**Pull request by vrtmrz**
Fix `this` of changesHandler.

The test is also written but works only for browsers.

### CODE REVIEW

**Comment by janl** [comment]
@vrtmrz thank you for this, but the test doesn’t actually pass. Could you have a look?

**Comment by janl** [comment]
@vrtmrz thank you for this. Unfortunately the test fails in CI: https://github.com/pouchdb/pouchdb/actions/runs/4063298839/jobs/6995899992 — I’m not sure I understand the error message about number of assertions either. Is there something you could do?

**Comment by vrtmrz** [comment]
Thank you for pointing it out! 
I am not sure about the value that assertion detected. However, we may also have timing problems.
I have rewritten the function to a callback style and will test it again.

**Comment by vrtmrz** [comment]
I have checked this test again. The assertion error you pointed out was probably not a problem with this test itself.
Perhaps, `test.viewadapter.js` is not waiting for both of `onsuccess`, and this test detects it.
I have not tested these assumptions, but I think we need to address and call `done()` or wrap events to Promise and await.

The browser-side tests became can be passed. May I ask you to review it again?

**Review by janl — APPROVED** [review]

**Pull request merged**
