### PR TITLE
(#5848) Fix constructor modifying options object

### PR DESCRIPTION
**Pull request by atgjack**
Using the same options object more than once was modifying the original
object. The options object was being cloned after the modification
rather than before. This fixes that and adds a test to make sure you can
use the same object again.

### CODE REVIEW

**Comment by nolanlawson** [comment]
LGTM, my only feedback is tests may be failing genuinely (I restarted them to double-check) and I'd also say `original` instead of `virgin` since it contains less cultural baggage. Thanks for the PR!

**Comment by atgJack** [comment]
I've updated the variable names, and fixed what was causing the tests to fail. 

I'm having trouble trying to run the test in Firefox on my rig, but everything else seems to pass. 
The Travis build is timing out, so I don't think it's an issue with the code, but I can't be totally sure.

Lemme know if I need to do anything else, I'm kind of a rookie in the PR department.

**Comment by nolanlawson** [comment]
Our tests are flaky and often require restarting individual tests in order to get a fully green run. I've restarted them and am happy with the PR; +1 when it's fully green.

**Comment by nolanlawson** [comment]
There is an apparent true failure that only occurs in the coverage tests, and only occurs for this test:

```
  1) test.views.js-local-http destroy using prototype:
     AssertionError: expected [ '_pouch_test' ] to have a length of 0 but got 1
      at tests/mapreduce/test.views.js:694:47
```

This is very weird and I'm not sure what's wrong. :confused:

**Comment by nolanlawson** [comment]
Sorry, this now has merge conflicts against master and would need some tweaking in order to pass our tests; please reopen if you get a chance to look at this. (I am removing old PRs/bugs to limit noise on the repo.)

**Pull request closed without merging**
