### PR TITLE
(#4207) - Add slack to places to constact us

### PR DESCRIPTION
**Pull request by daleharvey**
[skip ci]

### CODE REVIEW

**Comment by daleharvey** [comment]
I duplicated the list since it seemed useful in both places, having half a list wasnt great. If we dont want to duplicate could just link to it, not that fussed either way

**Comment by nolanlawson** [comment]
+1

**Comment by nickcolley** [comment]
I'd like to add the form to the website if that's cool? This'd be good to get in for now though.

**Comment by daleharvey** [comment]
On the website would be sweet, the website should probably have a similiar list as to this one

merged in https://github.com/pouchdb/pouchdb/commit/243758c51f6ee906af0d4821fe891577058cab6b

**Pull request closed without merging**
