### PR TITLE
corrected Python http server modules information

### PR DESCRIPTION
**Pull request by karolklp**

### CODE REVIEW

**Comment by nickcolley** [comment]
Since this is a beginners guide it might be confusing to have two options, especially as this isn't a python project. Maybe we should use https://www.npmjs.com/package/http-server or something?

**Comment by karolklp** [comment]
So let's leave only Python 3 option. It was released in 2008, so we it's almost certain, that beginner will have freshly-downloaded Python >= 3

**Comment by nickcolley** [comment]
My new install of Fedora ships with v2.X.

I'd say since python is fragmented in that respect we can't assume what version people will have.

**Comment by nolanlawson** [comment]
I think it's harmless to have instructions for both, although I do agree that Python is fragmented and the current situation is not ideal.

**Comment by daleharvey** [comment]
Yeh python 2.7.5 on my mac, I think both is simple enough

**Comment by nolanlawson** [comment]
canceled the travis build because it's not necessary

**Comment by karolklp** [comment]
Thanks guys, I wasn't aware of Python's fragmentation. Should we keep it that way or change it to https://www.npmjs.com/package/http-server like @nickcolley suggested? I like Python solution because it's nice trick for easy local server that may be useful..

**Comment by nolanlawson** [comment]
In my experience, new developers have an even harder time getting Node/npm up and running, because it's not installed by default on most systems.

**Comment by nickcolley** [comment]
I'm cool with having the both methods then I guess. :+1:

**Comment by nolanlawson** [comment]
Merged as 043498fa9dd54b6aec61b40619f6d139115f2f1a. I amended the commit on the way in to match our commit message format and to use a `#` comment instead of parens (just in case they copy-paste it). Thanks for the contribution! :)

**Comment by nickcolley** [comment]
Thanks @karolklp ! :+1: :tada:

**Comment by karolklp** [comment]
Thanks guys for great OSS experience :)

**Pull request closed without merging**
