### PR TITLE
Run CSG on Travis (squashed)

### PR DESCRIPTION
**Pull request by jchris**
This also adds Sync Gateway to the list of allowed failures.

### CODE REVIEW

**Comment by nolanlawson** [comment]
+1 when green

**Comment by jchris** [comment]
looks like it's ready to merge. thanks for the help everyone!

**Comment by jchris** [comment]
I could squash it again if that will help. I think it'd have to be a new pull request for that to work...

**Comment by nolanlawson** [comment]
No prob, I can squash it on the way in. Thanks for your effort; happy to have pretty much every *ouch server accounted for in our tests now. :)

**Comment by nolanlawson** [comment]
102874b54addb74a9dac8c1302cf0f1b95c5a481

**Comment by nolanlawson** [comment]
Related issues: https://github.com/pouchdb/pouchdb/pull/3521 https://github.com/pouchdb/pouchdb/pull/3423

**Pull request closed without merging**
