### PR TITLE
(#5304) - Service workers instead of Appcache for the website

### PR DESCRIPTION
**Pull request by nickcolley**
Continuation of https://github.com/pouchdb/pouchdb/pull/4846

### CODE REVIEW

**Comment by nickcolley** [comment]
Okay so this is working pretty well as is but I'm trying to think of a good way to let the user update the page like we have with appcache. I'm not sure this strategy is the right one with this in mind since a user needs to exit the page entirely for the newly generated worker to take over..

**Comment by nickcolley** [comment]
Okay this is ready to review, one con to this approach is that for people to see updates to pages they already have cached they need to leave the site and come back.

If we think that's important enough I can look at trying to handle that case better so let me know your thoughts. :+1:

**Comment by nolanlawson** [comment]
Hm, I would really rather not lose that "content updated, reload?" message if at all possible. I know there are ways to detect that the content changed; e.g. check out SVGOMG's method: https://github.com/jakearchibald/svgomg/blob/0f2ce1ace903d569337b72f57b8eb255b65177df/src/js/page/main-controller.js#L123-L127

**Comment by nickcolley** [comment]
@nolanlawson unless I'm mistaken the user needs to close the tab and then return for the service worker to become obsolete and be overridden?

**Comment by nolanlawson** [comment]
@nickcolley, no, you can update a service worker on-the-fly using `clients.claim()` and `skipWaiting()`. I admit my memory is fuzzy on which one exactly does what, but using one or both of those two, you definitely can.

**Comment by nickcolley** [comment]
Okay updated the PR with your feedback

**Comment by daleharvey** [comment]
Woot this is looking great, so having both appcache and serviceworkers on the page doesnt seem to conflict, https://github.com/slightlyoff/ServiceWorker/issues/697 suggests so too. Updates are working and seeing it working in both firefox and chrome, 👍 :)

**Comment by daleharvey** [comment]
Given the way appcache went I expect we will probably still see a few minor issues, but I think those will get found and fixed once its released, I tried checking as much as I can and all worked great for me so gonna push this then see how it goes :)

**Pull request merged**
