### PR TITLE
WIP - Use edge in CI

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by nolanlawson** [comment]
Trying some more IE/Edge combos. Historically IE10+Win8 worked (IIRC), and also Edge 17 is out now so there's a shot it will work.

TBH not much has changed in our IDB implementation since IE10 so testing IE10 (if it works) may be good enough. I'm not sure if there are WebDriver/Sauce/other reliability issues getting in the way of these tests passing.

**Comment by nolanlawson** [comment]
IE test is failing with "`testUtils` is not defined", Edge is failing with "No output has been received in the last 10m0s". Seems the latter is due to Sauce Labs but perhaps the IE test is fixable.

**Comment by daleharvey** [comment]
Yeh I am getting pretty close in https://github.com/pouchdb/pouchdb/pull/7297, the 10 failure is due to no promise polyfill, I am just skipping problematic tests (some of them we already sniff safari in), hoping this runs goes green for one, the last one timed out at like 90% done since it restarted

**Comment by nolanlawson** [comment]
I tested SauceLabs+Edge manually and got this. Seems the test is misconfigured not to use a tunnel or something?

screenshot 2018-05-26 13 40 21

**Comment by nolanlawson** [comment]
What's bizarre is that the other Sauce Labs tests are passing. Does the `sauceConnectLauncher` "know" to create a tunnel or something, but for Edge it's not doing it? I have a contact at Sauce Labs so I can reach out if this is a Sauce bug.

**Comment by nolanlawson** [comment]
Another option is to use localtunnel or ngrok. I've gotten in the habit of using ngrok for almost all my tests because it seems fairly stable.

**Comment by daleharvey** [comment]
Cheers for the help, got a working PR up @ https://github.com/pouchdb/pouchdb/pull/7297

**Pull request closed without merging**
