### PR TITLE
WIP - Only treat express-pouchdb running in fullCouchDB mode as a couchdb instance.

### PR DESCRIPTION
**Pull request by loic**
Refs https://github.com/pouchdb/pouchdb-server/pull/276.

cc @marten-de-vries

### CODE REVIEW

**Comment by marten-de-vries** [comment]
:+1: when green, although this will probably require a pouchdb-server release first, right?

**Comment by loic** [comment]
We'd lose the ability to test against `express-pouchdb` until a new version is released. I think we don't need to rush merging this one, `pouchdb-server` has an interim fix in its test own suite.

Issuing a new release of `pouchdb-server` with all plugins published from the monorepo is going to take some time IMO (i.e. we still need to come up with a strategy re versioning, etc.).

**Comment by marten-de-vries** [comment]
Ok, that sounds fine. I updated the title to prevent accidental merges in the meantime.

**Comment by marten-de-vries** [comment]
I think this is no longer blocked now?

**Comment by loic** [comment]
I think so, we just need to change the express-pouchdb server version in package.json.

**Comment by daleharvey** [comment]
Closing, happy to merge this when its ready + updated pouchdb-server

**Pull request closed without merging**
