### PR TITLE
Initial dollar sign escaped with unit tests.

### PR DESCRIPTION
**Pull request by filionf**
I am not sure if I have done everything properly, please let me know.

The unit test does not work when using pouchdb-server, but I suspect this is a difference between pouchdb-server and the real couchdb.

### CODE REVIEW

**Comment by daleharvey** [comment]
Hey cheers for this, and sorry for the delay

This isnt the area of code I am most familiar, however it looks like just above the clause you added there is the exact same clause but for . instead of $, I think we would probably want to have a single bit of code handle the escaping for both situations?

**Comment by filionf** [comment]
@daleharvey Done, I find this version clearer. Any idea why all the builds are failing?

**Comment by daleharvey** [comment]
Thanks, I think the build was failing due to saucelabs issues and nothing to do with your code, if you can rebase that would be great then I think this code would be good to go :) Apologies for the delay, working on making sure that doesnt happen again

**Review by daleharvey — CHANGES_REQUESTED** [review]
Meant to flag as requesting changes to keep track

**Comment by daleharvey** [comment]
Hrm, the test was failing on mapreduce tests but only in firefox + one adapter, not convinced the failure was down to this patch but couldnt restart, reopened is runnin gthe tests on .com so will see with that

**Comment by daleharvey** [comment]
And cheers for the rebase

**Comment by daleharvey** [comment]
ok and all passing now, dunno whats up with .org but new PR's shouldnt hit this issue.

Many thanks for the PR 👍

**Pull request merged**
