### PR TITLE
(#5128) - WIP - monorepo with separate modules

### PR DESCRIPTION
**Pull request by nolanlawson**
(#5128 for backstory.) This is just a work in progress to determine what's broken and what's not. It's also to provide more visibility into what I'm working on.

Stuff I still need to fix/address:

- more APIs are exposed now on `PouchDB.utils` in order for unit/coverage tests to pass. This can be avoided potentially, e.g. via a `pouchdb-for-testing` submodule
- reduce API surface of sub-modules (if possible? it might also not be a big deal to expose things like `PouchDB.adapter()` to users, but maybe we should avoid it)
- version independently? also might not be a big deal, except I'm worried about breaking changes in `pouchdb-utils`
- need PRs to Lerna and Rollup to enable the build script, currently using a fork of Lerna to make it work
- Cordova tests broken (do we care? maybe we should remove them)
- submodules need descriptions and READMEs
- how to handle optional deps? I say just skip optional deps now that folks have an npm-based workaround
- `npm run build-node` is gone, I don't even know if it's possible to resurrect

### CODE REVIEW

**Comment by nolanlawson** [comment]
Also here is the basic layout for the project:

- All packages are in `packages/` (Lerna convention)
- Packages define their dependencies like normal
- All packages define ES6 modules in `src` and build CJS into `lib`. Some projects are browser+node, and hence build `lib/index.js` and `lib/index-browser.js`, while others are vanilla and only build `lib/index.js`).
- `npm run build` uses Lerna to link the projects together: `lerna bootstrap && lerna run build` is all we need to build the whole project. Takes about 4 minutes on my machine for a clean install, about 3 minutes of which is `npm install` and the other 1 minute is building. (I'm also using local-npm, which helps.)
- Tests and doc scripts are at the top level. Lerna will be responsible for publishing; that's a TODO since I haven't finished the publish script yet.

**Comment by daleharvey** [comment]
How long is it from a single line change for that to be rebuilt to be tested in the browser? Since we switched to the ES6 build system iterating in the browser is pretty slow / hampered, I would really like to avoid regressing that further (we can also improve the current situation where the watch script rebuilds the world).

Losing greenkeeper is a shame, its been pretty useful, but not something day to day urgent and is something that will likely be supported in the future, we can even help out with that. Being able to avoid level / websql packages is going to be really nice, awesome job

**Comment by nolanlawson** [comment]
Incremental builds during development are definitely something I should add to this; thanks for bringing it up. I agree that the addition of ES6 modules slowed down development considerably due to the extra build step.

I believe during development we could avoid Rollup entirely and just use some kind of standard Browserify+Babelify+Watchify build process, which ought to give us fast increment builds because that's been supported in Browserify since forever (not supported in Rollup iirc). I'll get to work on that before removing `WIP` from this PR.

**Comment by nolanlawson** [comment]
closing in favor of https://github.com/pouchdb/pouchdb/pull/5178

**Pull request closed without merging**
