### PR TITLE
(#8185) - RangeError: invalid date

### PR DESCRIPTION
**Pull request by cyberquito**
I got the following error, when using bulkDocs with data I don't control:
RangeError: invalid date.

My current use case is importing data from mariadb; where some date fields have zeros: ''0000-00-00'. 

The error triggers when calling the Date.toISOString funciton.

Because it throws and error, the entire bulk batch won't get inserted.

I've patched the _clone_ function inside pouchdb-utils on line #57.

Also, I've added a test that throws an error on the main branch; You can compare it with this pull request where it doesn't break. The test is in: tests/misc/pouchdb-utils-clone.js

### CODE REVIEW

**Comment by shadow81627** [comment]
MySQL '0000-00-00' dates are invalid dates, MySQL 5.7 at least considers them invalid. Usually when I am migrating old MySQL databases I update the '0000-00-00' dates to NULL. What value does supporting '0000-00-00' dates give? I am pretty sure event considers '0000-00-00' invalid?

```js
new Date('0000-00-00')
Invalid Date
```

**Comment by shadow81627** [comment]
It looks like there are some linting errors that are failing the ci:

```bash
/home/travis/build/pouchdb/pouchdb/tests/misc/pouchdb-utils-clone.js
   8:2   error  Missing semicolon                semi
  13:2   error  Missing semicolon                semi
  16:30  error  Missing semicolon                semi
  25:3   error  Expected space(s) after "catch"  keyword-spacing
  41:3   error  Expected space(s) after "catch"  keyword-spacing
```

**Comment by cyberquito** [comment]
I've fixed the linting errors. The pouchdb-utils-clone.js should be done also with the current master branch code; this way you can see that it breaks.

I understand about nulling the  '0000-00-00' on  MariaDB. I still wish to continue with the pull request to make pouchdb more resilient on these particular cases.

**Comment by cyberquito** [comment]
I don't know how to past this test: continuous-integration/travis-ci/pr.

Can you give some guidance please?

**Comment by shadow81627** [comment]
It looks like the tests are having trouble connecting to saucelabs, it looks like it is a problem the other pull requests are having as well.

**Review by daleharvey — CHANGES_REQUESTED** [review]
Hi, thanks for the PR

You are editing a built file, thats why the entire file being added is part of the PR, the source code for `clone` is in https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-utils/src/clone.js

Also the tests in misc will not run in the browser and this seems like a test that we should run everywhere so `test.basics.js`
may be better? There is an example of some date based tests in the same file @ https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.basics.js#L715

**Comment by daleharvey** [comment]
The tests breaking were indeed part of the repo and not down to this patch, the issue has been fixed and a rebased push should show whether it is green or not

**Comment by cyberquito** [comment]
Hi, sorry for the delay. 

I've patched the src/clone.js file as suggested.
I moved the test to an existing test file: test.clone.js

Could you please trigger the integration tests?

Thank you,

Quito

**Comment by daleharvey** [comment]
Hey thanks for the update, the build failed with lint checks, you can run them with `npm run lint`

```
/home/travis/build/pouchdb/pouchdb/tests/unit/test.clone.js
  36:9   error  'obj2' is assigned a value but never used  no-unused-vars
  42:11  error  'obj2' is assigned a value but never used  no-unused-vars
  43:7   error  Expected space(s) after "catch"            keyword-spacing
```

If you want to test that a function doesnt throw you dont need to assign the return values. Also you need to remove the build file from our PR `packages/node_modules/pouchdb-utils/lib/index.js`

Once those are fixed this PR looks good, thank you

**Comment by cyberquito** [comment]
I've done this last changes. Could you retry the testing please?

**Comment by daleharvey** [comment]
Great thanks all passing now 👍

**Comment by cyberquito** [comment]
Great!

**Pull request merged**
