### PR TITLE
(#5096) - write blog post on prebuilt databases

### PR DESCRIPTION
**Pull request by nolanlawson**
Just a short blog post explaining how to do prebuilt databases. I made
a sample app while I was writing it, to verify that it worked. There
were a few hiccups, but it's totally doable and not excessively difficult.

### CODE REVIEW

**Comment by nickcolley** [comment]
Looks great to me, super useful :+1:

**Comment by schamp** [comment]
This looks great, I was just in the process of figuring out how to do it myself.  

I see for the website dump/load version, there's a check to see if the preload has already occurred.  I don't see anything equivalent for the cordova version.  At first glance, therefore, it looks like the read-write DB will be overwritten on each load.  Would you please consider adding a check to that case, too, or, if it's not a problem, an explanation?

**Comment by nolanlawson** [comment]
@schamp In fact it does have a similar check. I'll clarify that in the post.

**Comment by schamp** [comment]
That comment helps a lot, thanks, I had overlooked the catch() with all those new Promise(...) calls, it didn't stand out.

**Comment by nolanlawson** [comment]
3828467418c83ade2af0d5716cebd48139aa5013

**Pull request closed without merging**
