### PR TITLE
(#3532) - pouchdb 3.3.1 blog post

### PR DESCRIPTION
**Pull request by nolanlawson**
I should be able to do the actual release today or tomorrow.

### CODE REVIEW

**Comment by daleharvey** [comment]
+1, this is looking good, cheers

**Comment by nolanlawson** [comment]
I'll publish tomorrow and change the date on the way in.

**Comment by nolanlawson** [comment]
e04e93a6acfbb641a5db79606c0868bc8446a9ef

**Comment by nolanlawson** [comment]
https://github.com/pouchdb/pouchdb/commit/d807d00e834fd43546f8b1a08551329784e1ee3f

**Pull request closed without merging**
