### PR TITLE
(#3752) - fix jshint Promise error

### PR DESCRIPTION
**Pull request by nolanlawson**
jshint randomly started failing in Travis. So I updated
jshint and started using the new style of hinting
Promises, which involves this "futurehostile" thing.

handwavy handwavy the tests are passing again

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
Maybe a good time to look into eslint

**Comment by nolanlawson** [comment]
Haha, yeah, it seems like everyone is feeling that way these days. Would also be nice to start using ES6... :stuck_out_tongue:

**Comment by calvinmetcalf** [comment]
eslint has nothing to do with es6 it's just a more modular version of jshtin

**Comment by nolanlawson** [comment]
oh cool didn't know that. but yeah I just meant it feels like the whole community is moving away from jshint, same way we moved away from jslint...

**Comment by nolanlawson** [comment]
Also +1? :)

**Comment by jo** [comment]
:+1:

**Comment by nolanlawson** [comment]
822f002ee69805b344965aae2070ab88c41141a2

**Pull request closed without merging**
