### PR TITLE
(#3374) - Fix some uglify warnings

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by daleharvey** [comment]
Just some unused vars from the output of uglify, the rest are browser browserify and may take a look at fixing

**Comment by daleharvey** [comment]
Cancelled the test run because I would like to see result of https://github.com/pouchdb/pouchdb/pull/3375 first, but will restart

**Comment by marten-de-vries** [comment]
Looks good. :+1: when green. :)

**Comment by daleharvey** [comment]
Awesome thanks - https://github.com/pouchdb/pouchdb/commit/fba56720db31a4509cc0c670de67a2d5b350be20

**Pull request closed without merging**
