### PR TITLE
(#3921) - speed up updateDoc()

### PR DESCRIPTION
**Pull request by nolanlawson**
For now, I just want to see if the tests are passing.

This is a slightly dangerous optimization and may require a migration.
The fact that it seems to be working without migrations kinda worries
me; I think I might need to add a new migration test to catch it.

Also I have not measured the performance boost yet, but this is
pre-caching a lot of values as well as speeding up `revExists()`.

### CODE REVIEW

**Comment by nolanlawson** [comment]
Also I don't plan on getting this into 4.0.0, so no rush.

**Comment by nolanlawson** [comment]
I'm stunned this actually passed. This weekend I'll get some numbers on the perf boost and try to confirm whether or not we need a migration.

**Comment by nolanlawson** [comment]
I've added a migration test, so I feel confident now that this PR is good to go.

Speedup is slight, but any speedup is good, right? Numbers are from a low-spec Acer Aspire laptop running Linux Mint for the `bulk-inserts` test:

Chrome 11 (websql): 33002ms -> 32277ms
Chrome 44 (idb): 15690ms -> 14988ms
iojs 2.5 (leveldb): 4878ms -> 4862md

**Comment by daleharvey** [comment]
The failure is just a coveralls issue that seems to happen on branches that arent completely up to date
+1 on extra migration tests - https://github.com/pouchdb/pouchdb/commit/cd1357a6a63a048a71336a336e516a3d02afad6e

**Pull request closed without merging**
