### PR TITLE
(#3946 #3758) - add buffer.type, test types

### PR DESCRIPTION
**Pull request by nolanlawson**
Two goals here:

1. Test `blob.type`, which we actually weren't testing before
   (#3946).
2. Add an ad-hoc `type` to buffers, for consistency across
   Node and the browser (#3758).

### CODE REVIEW

**Comment by nolanlawson** [comment]
Everything passing except for Couch master.

**Comment by daleharvey** [comment]
:+1: but would prefer to land on green (ie when couch master tests are green or allowed fails)

**Comment by nolanlawson** [comment]
Seems after 3 or 4 retries, I managed to make it green. Maybe the Couch master failures are intermittents after all?

**Comment by nolanlawson** [comment]
Green, so merging. I feel unsure about actually documenting this `buffer.type` behavior, since it's kinda non-standard and weird, and I'm gonna wait for @calvinmetcalf to tell me if I'm crazy and going against the grain of Node or not. But if he thinks it's okay, then we can start using it to avoid an extra method call in `express-pouchdb` (because there's no need to do a `get()` in addition to a `getAttachment()` anymore), so @marten-de-vries you may be interested in this. Else we should just modify the tests to do an `if (isBrowser)` check.

**Comment by nolanlawson** [comment]
2bd898d07fd23a21f000af713e0dd63983f1b4a8

**Pull request closed without merging**
