### PR TITLE
(#3873) - update levelup, leveldown, & friends

### PR DESCRIPTION
**Pull request by nolanlawson**
This is merely to reproduce a new sublevel error.
@juliangruber fixed the old error (https://github.com/dominictarr/level-sublevel/pull/96), but there's a new one:

```
  1) test.all_docs.js-local Testing all docs:

      correct number of results
      + expected - actual

      +4
      -0

      at /Users/nlawson/workspace-node/pouchdb/tests/integration/test.all_docs.js:33:36
      at /Users/nlawson/workspace-node/pouchdb/lib/deps/toPromise.js:20:11
      at doNTCallback0 (node.js:408:9)
      at process._tickCallback (node.js:337:13)
```

### CODE REVIEW

**Comment by juliangruber** [comment]
can you maybe pinpoint a specific update in one dependency that causes the bug?

**Comment by nolanlawson** [comment]
Yup I plan on writing a reproducible test case and hopefully fixing it myself. 99% sure the bug is in sublevel.

**Comment by nolanlawson** [comment]
It was just sublevel v5 -> v6 migration issues. Passing in leveldown for me now; hopefully MemDOWN and LocalStorageDOWN still work too.

**Comment by nolanlawson** [comment]
Ugh, memdown and localstoragedown are now failing in the browser, apparently due to some super-subtle through2/Transform/Duplex/streams thingie:

```
TypeError: this.once is not a function
    at DestroyableTransform.Duplex (http://127.0.0.1:8000/dist/pouchdb.memory.js:6143:8)
    at DestroyableTransform.Transform (http://127.0.0.1:8000/dist/pouchdb.memory.js:7288:10)
    at new DestroyableTransform (http://127.0.0.1:8000/dist/pouchdb.memory.js:21216:13)
    at http://127.0.0.1:8000/dist/pouchdb.memory.js:21298:12
    at http://127.0.0.1:8000/dist/pouchdb.memory.js:21256:12
    at http://127.0.0.1:8000/dist/pouchdb.memory.js:856:27
    at countDocs (http://127.0.0.1:8000/dist/pouchdb.memory.js:230:12)
    at http://127.0.0.1:8000/dist/pouchdb.memory.js:815:5
    at tryCode (http://127.0.0.1:8000/dist/pouchdb.memory.js:254:11)
    at http://127.0.0.1:8000/dist/pouchdb.memory.js:301:7
```

^ For some reason, Duplexes were correctly inheriting EventEmitter prototype functions before, but not anymore somehow.

**Comment by calvinmetcalf** [comment]
That is an issue with an out of date version of readable-stream make sure
the dep is up to date

**Comment by nolanlawson** [comment]
Thanks @calvinmetcalf; you probably just saved me another hour of searching through https://github.com/nodejs/readable-stream :wink:

Updating browserify to 11.0.0 solved the issue; gonna update through2 to 2.0.0 while I'm in there to make sure it's using the latest readable-stream as well. Note to self: update one thing, go back and update a bunch of other things too.

**Comment by daleharvey** [comment]
Is this still WIP, are there migrations we need to do for this ourselves? awesome job on getting it green

**Comment by nolanlawson** [comment]
No migrations necessary, although in the future we will probably want to stop using `sublevel/legacy`.

This is WIP imo until https://github.com/dominictarr/level-sublevel/pull/96 is merged, because I feel uncomfortable depending on a git commit rather than an npm version.

**Comment by daleharvey** [comment]
Ah yeh definitely hold off until we are against a released version, but a huge :+1: when that lands, and major props for going into level and fixing stuff in there to get this working, thats awesome

**Comment by nolanlawson** [comment]
Looks like sublevel was published at 6.5.0; I will try that version and then re-run the tests for this PR.

**Comment by daleharvey** [comment]
Lets do this! https://github.com/pouchdb/pouchdb/commit/8fd74079cb799d47a2a7679a7ed74d9c0c1aeacc, looks to break express-pouchdb-router, will take a look at that

**Pull request closed without merging**
