### PR TITLE
Build in Node 5, `npm pack`, then test in Node 6 and Node 0.10

### PR DESCRIPTION
**Pull request by nolanlawson**
Forgot about `npm install --production`. Let's try this again.

Follow-up to #5184 .

### CODE REVIEW

**Comment by nolanlawson** [comment]
muahahaha, it works! No more need to use the same version of Node for both compiling and testing!

**Comment by nolanlawson** [comment]
OK, this is a proposed commit on top of #5178, which explicitly builds in Node 5 and then tests in the other Nodes. 0.10 and 6 are still allowed failures, but perhaps we can remove them from allowed failures if this becomes stable enough (they passed in one Travis run, at least).

**Comment by nolanlawson** [comment]
File an issue on Lerna for Node 0.10: https://github.com/lerna/lerna/issues/157

**Comment by nolanlawson** [comment]
Filed an issue on Rollup for Node 6: https://github.com/rollup/rollup-plugin-node-resolve/issues/38

**Comment by daleharvey** [comment]
👍 when green, when this gets merged we should open an issue tracking both ^ and remove this code when its no longer needed

**Comment by nolanlawson** [comment]
Will do!

**Comment by nolanlawson** [comment]
^ Rebased, also went ahead and removed 0.10 and 6.0 from allowed failures; they seem to be passing pretty consistently now, and I have more confidence they'll work due to being built in one version.

**Comment by nolanlawson** [comment]
@daleharvey Also I tend to disagree that the code should be removed when Lerna/Rollup fix those issues. Reasons being:

1. Testing in Node 0.10 is one thing; building in Node is entirely another. The more Node diverges, the more difficult it will become to use the same code for building and testing.
2. This script reveals bugs that wouldn't otherwise be discovered, e.g. because of an error in `.npmignore` or `"files"` causing the wrong files to not be published. `npm pack` gives us exactly the version of `pouchdb` that would be `npm publish`ed, hence identifying those potential errors.

The code is indeed ugly, which is why I isolated it to `bin/npm-pack-in-travis.sh` so it was obvious what it was doing.

**Comment by nolanlawson** [comment]
Green!

**Pull request merged**
