### PR TITLE
Issue #7458: Nested $and not working in pouchdb-find.

### PR DESCRIPTION
**Pull request by BarboraNovotna**

### CODE REVIEW

**Comment by garrensmith** [comment]
This looks really good. I just need a little time to go over it before merging. Can you give me a few days and I'll get back to you on this.

**Comment by garrensmith** [comment]
This looks good, thank you. Could you fix the linting issue https://travis-ci.org/pouchdb/pouchdb/jobs/448405064 and then I can merge once the tests are green.

**Comment by garrensmith** [comment]
yes they will

**Comment by BarboraNovotna** [comment]
I see that some tests failed but it seems that it is not related to my issue... Could you take a look at it?

**Comment by daleharvey** [comment]
Sorry about that @BarboraNovotna, a change in travis broke our tests, could you possibly rebase and repush this and and can finally land once the tests are green, cheers

**Comment by daleharvey** [comment]
Not looked into this a bunch, but looking at the failures I am guessing the same problem that I just seen in https://github.com/pouchdb/pouchdb/pull/7496, we use es5 in pouch and it seems that es6 looks like it breaks the build, I can see a const in there so probably it

**Comment by BarboraNovotna** [comment]
"docker: Error response from daemon: driver failed programming external connectivity on endpoint vigorous_shockley" - looks like env issue

**Comment by daleharvey** [comment]
The failure was an unrelated intermittent. Apologies for the delay here, this is longer than we would like to be getting stuff merged but your PR came right at the same time as holidays + some test breakages

Everythings good now, thanks for your contribution

**Pull request merged**
