### PR TITLE
(pouchdb/mapreduce#251) - fix idb destroy() race

### PR DESCRIPTION
**Pull request by nolanlawson**

### CODE REVIEW

**Comment by nolanlawson** [comment]
Better wait for a success from IE before merging. Also I might be able to rewrite the test from mapreduce and move it here.

**Comment by daleharvey** [comment]
Hrm, this could possibly be the issue that was causing https://github.com/pouchdb/pouchdb/pull/3385 to fail

**Comment by nolanlawson** [comment]
Yeah I'm also seeing another race related to Chrome+IDB+destroy. Trying to track it down.

**Comment by daleharvey** [comment]
Green in iphone and ie :) 

https://github.com/pouchdb/pouchdb/commit/0bc2c4d6e203bf225483483ec47a2cefdfc41cec

Cheers

**Pull request closed without merging**
