### PR TITLE
(#4318) - 4.0.2 release blog post

### PR DESCRIPTION
**Pull request by nolanlawson**
This just contains the changes that I intend to commit to master. The
4.0.2 code itself will be built and tested in a separate branch,
since it contains some reverts.

### CODE REVIEW

**Comment by Charlotteis** [comment]
+1 From me!

**Comment by daleharvey** [comment]
Yup :+1: cheers

**Comment by nolanlawson** [comment]
d845476fe6b9fc94fd7e38685d9e08fc7310111c

**Comment by gr2m** [comment]
That is so awesome, thanks so much!

**Pull request closed without merging**
