### PR TITLE
using extend instead of js-extend which is working with rollup-plugin-commonjs

### PR DESCRIPTION
**Pull request by ckaeslin**
Not sure why tests in https://github.com/pouchdb/pouchdb/pull/5751 failed.
But in order to help making progress (for ionic people), I'm providing here a version with https://www.npmjs.com/package/extend instead of https://www.npmjs.com/package/js-extend.

I tested this locally and verified that it's working with latest ionic-app-scripts without any additional custom configuration.

### CODE REVIEW

**Comment by daleharvey** [comment]
It looks very much like #5751 is failing intermittents, its likely that they can be restarted, go green and that PR can get merged today

**Comment by ckaeslin** [comment]
I think https://github.com/pouchdb/pouchdb/pull/5751 needs unit tests for included js-extend to pass the requested line coverage of 100%.

**Comment by daleharvey** [comment]
Yup you are right, there is one line not being covered, could be an ignore if its trouble to test

**Comment by ckaeslin** [comment]
tests are here: https://github.com/vmattos/js-extend/blob/master/test/suite.js
since the code is copy from there

**Comment by ckaeslin** [comment]
closing in favor of https://github.com/pouchdb/pouchdb/pull/5754

**Comment by nolanlawson** [comment]
fixed in pouchdb 6.0.7

**Pull request closed without merging**
