### PR TITLE
(#6053) - assign defaults to new pouch db instance in PouchDB.plugin() (rebased)

### PR DESCRIPTION
**Pull request by nolanlawson**
Rebased version of #6195

### CODE REVIEW

**Comment by nolanlawson** [comment]
Made some minor stylistic changes, thanks for the PR @kartikagarwal1993 !

**Comment by nolanlawson** [comment]
Ugh I'm really sorry, but squashing it somehow made me the author. :( We don't force-push to master, so there's no way for me to change it. Please don't feel discouraged about contributing; sorry for my mistake!

**Comment by nolanlawson** [comment]
OK I figured out a workaround: I reverted the commit and then did a new commit (3e454a35643b3189552aa5166f925ad1fd755fee) with you as the author. Thanks again!

**Comment by kartikagarwal1993** [comment]
@nolanlawson Thanks a lot, for guiding through this issue and also for the extra steps you had to do for giving credits to me. (It was my first ever open source contribution)

**Comment by nolanlawson** [comment]
Welcome aboard! In that case, I'm glad I went to the extra effort. :)

**Pull request merged**
