### PR TITLE
Clarify eHealth Africa text

### PR DESCRIPTION
**Pull request by adamvert**
I'm one of the eHealth Africa devs. We just put together this short text to clarify slightly what we're using PouchDB for. Thanks for the shout out!

### CODE REVIEW

**Comment by jo** [comment]
:+1

**Comment by nickcolley** [comment]
Great!

**Comment by adamvert** [comment]
@nickcolley fixed the line wrapping

**Comment by daleharvey** [comment]
Awesome, thanks a lot for this, merged @ https://github.com/pouchdb/pouchdb/commit/8b2420b18135e28ce6c964afe7f5064453caa23e

**Pull request closed without merging**
