### PR TITLE
(#4788) - Follow up to ensure test will fail before fix

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by daleharvey** [comment]
Follow up to https://github.com/pouchdb/pouchdb/pull/4804, verified that the test fails before the fix and passes after

**Comment by bbenezech** [comment]
I didn't need to call it twice to have a repro on my machine. Not sure why.

**Comment by nolanlawson** [comment]
:+1:

@bbenezech Weird, well let's take the safe route and call it twice. It only failed for me on the second call (Chrome on OS X).

**Comment by daleharvey** [comment]
green and landed, cheers - https://github.com/pouchdb/pouchdb/commit/7f2321b47ad69ca4214b0f6f03866a03dc21c587

**Pull request closed without merging**
