### PR TITLE
(#2239) - Remove npm run shell

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by daleharvey** [comment]
This had a whole raft of bugs and hasnt proved to be very useful, I would like to do something along the same idea, but figure out a way to do it that isnt so restrictive / error prone

**Comment by nolanlawson** [comment]
I agree; I've never used it. Let's also remove the description from TESTING.md.

**Comment by daleharvey** [comment]
Good catch, forgot about that

**Comment by daleharvey** [comment]
Merged

https://github.com/pouchdb/pouchdb/commit/b70b99300a6dc05042dc13be721159d56ffd2403

**Pull request closed without merging**
