### PR TITLE
Make a test pass for Sync Gateway

### PR DESCRIPTION
**Pull request by jchris**
This makes test.replication.js-local-http by skipping assertions
that expect database info to contain a doc count. If there is a
doc count we make sure it's correct.

Also Sync Gateway sends an additional _revisions field which was
messing up deep equal, so instead now I'm testing directly for
the field we expect.

### CODE REVIEW

**Comment by jchris** [comment]
passes

It's alive!

**Comment by jchris** [comment]
This shouldn't pass on the Travis version of SG yet, the changes in SG to make it happen are still on the SG master branch.

**Comment by jchris** [comment]
I think that failure was spurious, maybe merge anyway?

**Comment by nolanlawson** [comment]
I tend to restart the failed jobs just to be safe. It's also good motivation to fix the intermittents :P.

You should have received an invite to join the pouchdb org; after that if you log into Travis, you can restart the jobs too. I've restarted this one, though.

**Comment by nolanlawson** [comment]
Green and merged. :) cd656e001c89e04a1b8e95f126a5e95bc7b1f287

**Pull request closed without merging**
