### PR TITLE
(#3755) - Faster replicate from down server test

### PR DESCRIPTION
**Pull request by jo**
By configuring a `10ms` ajax timeout.

### CODE REVIEW

**Comment by nolanlawson** [comment]
:+1: when green.

**Comment by jo** [comment]
Test failure because of https://github.com/pouchdb/pouchdb/pull/3730#issuecomment-94857512

**Comment by jo** [comment]
here: https://travis-ci.org/pouchdb/pouchdb/jobs/59411214

**Comment by jo** [comment]
Rebased to master (which has #3752). Now [waiting to hear about 228ef9e](https://travis-ci.org/pouchdb/pouchdb/builds/59517123)...

**Comment by jo** [comment]
finally green :)

**Comment by nolanlawson** [comment]
aef8094

**Pull request closed without merging**
