### PR TITLE
(#6014) - update memdown to 1.2.4

### PR DESCRIPTION
**Pull request by nolanlawson**
Based on some quick performance testing, this seems like it should be a big boost thanks to the nextTick -> immediate change. I can run some benchmarks once we see that it's green.

### CODE REVIEW

**Comment by nolanlawson** [comment]
This is a true failure. Firefox is throwing up the "a script is causing this page to run slowly" dialog which AFAIK is caused by `immediate` getting caught in an infinite loop.

Subbing in `window.setTimeout` for `immediate` fixes the issue but also slows it down a ton due to increased latency. I think we should either try to fix `immediate` in memdown or use another `nextTick` implementation.

**Comment by nolanlawson** [comment]
Can be repro'd in Chrome as well

**Comment by nolanlawson** [comment]
I tried immediate 3.0.6 and 3.2.3 and both exhibit this problem. This may take quite a bit of effort to reduce the error and fix it in memdown.

@calvinmetcalf you may be interested in this issue. To repro:

```
hub clone pouchdb/pouchdb --single-branch --branch memdown-1.2.4 --depth 1
cd pouchdb
npm i && npm run dev
# open localhost:8000/tests/integration?grep=local in a browser
```

**Comment by calvinmetcalf** [comment]
Hm have you checked out microtask? That might fix your issue assuming it's that recursive usage of immediate is pegging the event loop

**Comment by nolanlawson** [comment]
OK, I've determined that `microtask` exhibits this behavior, and that a simple `var resolved = Promise.resolve(); function nextTick(fn) { resolved.then(fn) }` also exhibits it. So it's either a bug in memdown, in pouchdb, or in our tests apparently. I'll keep digging.

**Comment by nolanlawson** [comment]
Figured it out. The problem was that a couple of our tests weren't really prepared for the underlying adapter to be based on microtasks, and could run into an infinite loop.

So basically memdown is so fast now, it revealed a bug in our tests. :smiley:

**Comment by calvinmetcalf** [comment]
> Hm have you checked out microtask?

I meant macrotask but glad you were able to figure it out 😄

**Pull request merged**
