### PR TITLE
(#4071) - fix code coverage of sync()

### PR DESCRIPTION
**Pull request by nolanlawson**
`sync()` is now at 100% code coverage.

### CODE REVIEW

**Comment by daleharvey** [comment]
So this looks mostly good, but fairly worried about the need for `setTimeout`s in these tests, so taking a look at whether they are absolutely required

**Comment by nolanlawson** [comment]
Yeah I just wanted to make sure that the `complete` callbacks get called after the `change` callbacks, since the order is unspecified. I believe in practice, though, `change` comes before `complete`, so they may be safe to remove.

Note that they are setTimeouts with 0, though! So I'm not trying to do any janky sleeps here. :stuck_out_tongue:

**Comment by daleharvey** [comment]
ok cool, yeh they arent the 'just wait for x to happen, they are all yeilding on something sync happening so I 'think' its all fine, so :+1: but will keep an eye on failures

**Comment by daleharvey** [comment]
Merged in https://github.com/pouchdb/pouchdb/commit/83d7e10d139897ac3c6c26e38e13c5ca05d14c28

**Pull request closed without merging**
