### PR TITLE
(#5161) - Remove sticky polyfill

### PR DESCRIPTION
**Pull request by daleharvey**
[skip ci]

### CODE REVIEW

**Comment by daleharvey** [comment]
So I am pretty close to the edge on whether we should do this, on one hand we wont be broken in chrome beta / dev (and so potentially future chromes when they release), on the other chrome (only) users may have to scroll a bunch extra in the desktop view. Chrome users will eventually get fixed (`position: sticky` is currently being worked on, I think its expected in July)

**Comment by nickcolley** [comment]
I'd be :+1: if Chrome is about to ship sticky...

**Comment by daleharvey** [comment]
Its slated for 52, however looking like its having problems sticking https://bugs.chromium.org/p/chromium/issues/detail?id=231752#c28

**Comment by daleharvey** [comment]
So yeh, its gonna be a while for chrome to support position sticky, will just have to hope chrome beta fixes this

**Pull request closed without merging**
