### PR TITLE
(#3197) - Remove PouchDB.destroy usage in tests

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by daleharvey** [comment]
Picked up the simpler ones just to make sure to keep it green, following up with the rest shortly

**Comment by daleharvey** [comment]
All dont aside the last one in `utils.js`, got some failures removing it so will leave that one till last

**Comment by willholley** [comment]
LGTM

**Comment by daleharvey** [comment]
Awesome thanks - https://github.com/pouchdb/pouchdb/commit/b4983cfeaece1a19f65b764730ca5a07d25e2500

**Pull request closed without merging**
