### PR TITLE
(#4071) - extract out more browser-only code

### PR DESCRIPTION
**Pull request by nolanlawson**
This increases code coverage from 36.91% to 87.66%. There
is no more code that uses `if (process.browser)`.

I also moved most of the ajax-related stuff into an `ajax/`
folder to make the code easier to read.

### CODE REVIEW

**Comment by nolanlawson** [comment]
Follow-up to https://github.com/pouchdb/pouchdb/pull/4072

**Comment by nolanlawson** [comment]
This PR also reduces the min+gz size from 49228 to 49119.

**Comment by nolanlawson** [comment]
Accidentally messed up the package.json again (had disabled the cache-busting), but should be fixed now.

**Comment by daleharvey** [comment]
Nice, :+1:

**Comment by nolanlawson** [comment]
22ed9da3f1677a4f7b99db93db44df495bd25dd1

**Pull request closed without merging**
