### PR TITLE
Add script: repeat-perf-test.sh

### PR DESCRIPTION
**Pull request by alxndrsn**
This script allows running the performance test suite against one or more different versions of the codebase.

Also changed:

* ~ci: `browser-adapter` and `couchdb-browser` now use `.min.js` versions of adapters and plugins in addition to `pouchdb.min.js`~ separate PR: https://github.com/pouchdb/pouchdb/pull/8870

Example:

```
$ ./bin/repeat-perf-test.sh 03d233f99e37d876332af82c153725d52229ef5a 3682a8ac71df9acd8c2fe40db2175c3c8ceb0304

[repeat-perf-test.sh] Running perf tests endlessly on:
[repeat-perf-test.sh] 
[repeat-perf-test.sh]   1. 03d233f9 Add script: repeat-perf-test.sh
[repeat-perf-test.sh]   2. 3682a8ac Add BenchmarkJsonReporter
[repeat-perf-test.sh] 
[repeat-perf-test.sh] Press <enter> to continue.


[repeat-perf-test.sh] Checking out 03d233f99e37d876332af82c153725d52229ef5a...
...
```

Useful with https://github.com/pouchdb/pouchdb/pull/8759 if you want to run multiple perf iterations and then compare the results for different adapters, or different implementations of the same adapter.

### CODE REVIEW

**Comment by alxndrsn** [comment]
This is still repeatedly rebuilding pouch in `bin/dev-server.js`.

**Comment by alxndrsn** [comment]
TODO

* [ ] confirm if all env vars require explicit defaults in the script
* [ ] consider if `USE_MINIFIED` should just be implicit if `PERF=1` or running the perf tests, or should be included in a separate PR

**Review by garethbowen — APPROVED** [review]
Nice.

**Comment by alxndrsn** [comment]
TODO: rebase onto #8870

**Comment by alxndrsn** [comment]
May be affected by https://github.com/pouchdb/pouchdb/pull/8866

**Pull request merged**
