### PR TITLE
Ignore CSG "_user" entries in the changes feed.

### PR DESCRIPTION
**Pull request by jchris**
This is the last bug that needs to be fixed before I was able to get CSG and PouchDB's TodoMVC example syncing.

This depends on applying my [CORS pull request to SG master](https://github.com/couchbase/sync_gateway/pull/695) before it will work.

### CODE REVIEW

**Comment by nolanlawson** [comment]
LGTM, added a comment on the way in. Thanks!

**Comment by nolanlawson** [comment]
Also put the return on the next line; matches our style better. Surprised jshint didn't say anything.

Sadly though, I broke our combo again. Forgot to check the format of the commit message. No biggie. 7a7d0310afcc6cfca0509e36d75986f6ce62d313

**Comment by jchris** [comment]
BTW if you use the [example CORS config](https://github.com/couchbase/sync_gateway/blob/master/examples/cors_admin_party.json) with Sync Gateway, and set the right URL in [the PouchDB getting started app](https://github.com/nickcolley/getting-started-todo/blob/master/js/app.js#L14) everything works great!

**Comment by nolanlawson** [comment]
@jchris That is awesome. :) Looking forward to more Couchbase+PouchDB tutorials! Or we could add that as a little info box in the Get Started guide.

**Pull request closed without merging**
