### PR TITLE
(#5309) Error check in _allDocs / allDocsInner

### PR DESCRIPTION
**Pull request by stockulus**
more details and why on https://github.com/pouchdb/pouchdb/issues/5309

### CODE REVIEW

**Comment by daleharvey** [comment]
So the correct fix for this is https://github.com/pouchdb/pouchdb/issues/3224, having us fallback from invalid data when we read it is a nasty position to get into, This is also going to be extremely difficult to test correctly. 

I think we can do it this one time, but any further work should be on ensuring the data that is written is not corrupt, got a question about the actual implementation though

```js
+            if (!err) {
+              allDocsInner(data);
+            }
```

If there is an error, it seem from the code this would let that call hang and do nothing, is that what happens? should this not have an 

```js
} else { 
  callback(err);
}
```
as well?

**Comment by stockulus** [comment]
because it is not pushed to the result (results.push(doc) in function allDocsInner) it will be ignored in the read completely. I do not see a other usefull behavior and in this adapter is no debug logging. 

without this check you get a error, because allDocsInner is called with null and options include_docs.

**Comment by daleharvey** [comment]
ah ok it continues silently. Yeh I am really beginning to feel we should not paper over this, it means `db.allDocs` and `db.allDocs({include_docs: true})` are going to return different results right? 

At the very very least it needs a large warning, however even at that point the users data is corrupt, subsequent reads are going to fail and I think anything other than a fatal error is misleading the user

**Comment by stockulus** [comment]
yes, db.allDocs and db.allDocs({include_docs: true}) are going to return different result.

-> So you'd prefer a callback(new Error('Database Corrupt') as result?

**Comment by daleharvey** [comment]
I think so, at this point the data is corrupt and we can make no guarantees about what data is coming out of pouchdb, I dont think there is a reasonable way for pouch or the user for that matter to fallback aside from restore from backup and we should make that clear to them

**Comment by stockulus** [comment]
got you and understand it; thougth it does not help me;

i can change it, that it callbacks with reasonable Error.

**Comment by daleharvey** [comment]
Yeh its not a great situation for our data to become unrecoverably corrupt, however I think we do need to be honest about it. 

In good news, the structure I used for https://github.com/pouchdb/pouchdb/tree/master/packages/pouchdb-adapter-indexeddb should be directly portable to leveldb and should almost by default have us in a situation where we will not be able to write corrupt data, I will investigate the port shortly

**Comment by stockulus** [comment]
Sounds great. Looks much cleaner too. I think I will live with a copy in the meanwhile.
Properly I take the indexeddb adapter as blueprint, to build a pouchdb-adapter for Async Storage without leveldb-bridge

**Comment by daleharvey** [comment]
Yeh I think that is a really good plan, the adapter itself is not a huge amount of code and based on asyncStorage should likely be even less code than idb / leveldb, if you need any help then please feel free to ask about it

**Comment by daleharvey** [comment]
@stockulus just checking, are you planning on following up on this or focusing on replacing this with the asyncStorage adapter? Can dupe it to https://github.com/pouchdb/pouchdb/issues/3224 if you are focusing on asyncstorage

**Comment by stockulus** [comment]
I planing to focus on asyncstorage, so we can close this Pull Request. The pouchdb_react_native currently depends on a Package Copy, so it's ok.

Think it does not make sense to put a lot of afford here, if it gets rewritten anyway.

If possible, I'd like you to review the Code once the asyncstorage adapter is ready.

**Comment by daleharvey** [comment]
Yup I would be happy to, its up to you but we may want to think about having it in the pouch repo once it is completed

**Comment by stockulus** [comment]
I'd like it, if it gets part of the pouchdb repo.

**Comment by nolanlawson** [comment]
@stockulus looking at this "fix", I get the impression that there must be a bug somewhere in `asyncstorage-down`. I mean, we have used this code in 5 different *down adapters (leveldown, memdown, localstorage-down, fruitdown, level.js), and never seen an issue. So that tells me that there's a 99% chance the bug is in `asyncstorage-down`.

Still I agree with @daleharvey that the error ought to be handled, and yeah, we should fix it in #3224.

**Comment by stockulus** [comment]
I am still in the adapter learning. so i am not that sure. The Situation i have, is an write millisec before the application get killed; Not the easiest Sitiuation and not "real Word". 

Anyway I started writing an adapter for pouchdb without using the leveldown adapter.
https://github.com/stockulus/pouchdb-react-native/tree/master/packages/pouchdb-adapter-asyncstorage-pure/src
(is just the beginning, currently thinking how to get transactions without having transactions, testing with AsyncStoreage if MutiSet is good enougth)

**Pull request closed without merging**
