### PR TITLE
(#5412) - markdownify headings

### PR DESCRIPTION
**Pull request by williambelle**
I hope this doesn't change the appearance of anything else on the site.

### CODE REVIEW

**Comment by daleharvey** [comment]
2 small notes, what is this change for? And also if you are doing documentation only PR's it would be great if you could put `[skip ci]` in the commit message, just saves the resources of running the entire suite, although its easy enough for me to cancel it cheers

**Comment by daleharvey** [comment]
Ah, would this fix https://github.com/pouchdb/pouchdb/issues/5412 ? taking a look now

**Comment by williambelle** [comment]
Ok, no test with documentation.

Yes, it's supposed to correct #5412.

**Comment by nolanlawson** [comment]
I can confirm this fixes the issue. Merci, William! :wink:

**Pull request merged**
