### PR TITLE
(#2035) - WIP - get rid of cors proxy

### PR DESCRIPTION
**Pull request by nolanlawson**
I'm really tired of this thing. It
slows down the test and causes
weird bugs occasionally. Let's try
removing it.

### CODE REVIEW

**Comment by nolanlawson** [comment]
Shoot, apparently when I run couch master using `python dev/run -n 1 --with-admin-party-please`, there's no config database, so I can't enable CORS. @kxepal Do you have any idea how to fix that?

**Comment by kxepal** [comment]
Sure I have (: /_config is not available on cluster port (x5984), but it still is on local one (x5986). And this means that you'll need to configure CORS on the each mode in order to sync their behavior.

**Comment by nolanlawson** [comment]
I think this will be blocked for the moment on couchdb-master (@rnewson is looking into it!), but it's nice to see what fails in Travis.

**Comment by nolanlawson** [comment]
Blocked by this Couch issue: https://issues.apache.org/jira/browse/COUCHDB-2705

**Comment by nolanlawson** [comment]
Whoa, couch-master is actually working in Travis somehow. But unfortunately iPhone doesn't work, and i cannot repro. Trying to add some new cors headers.

**Comment by nolanlawson** [comment]
Meh, I'm not going to try to debug Travis-only errors. It's not worth my time.

**Pull request closed without merging**
