### PR TITLE
(#6277) - fix pouchdb-find null error

### PR DESCRIPTION
**Pull request by nolanlawson**
Rebased/tested version of https://github.com/pouchdb/pouchdb/pull/6313

### CODE REVIEW

**Comment by nolanlawson** [comment]
I've written a test, which I can confirm fails before the fix but succeeds after. Also it's consistent with CouchDB 2.0's output.

**Comment by nolanlawson** [comment]
Tests are failing because we need to link pouchdb-server's deps back to the packages in the monorepo. Tests should pass after that.

**Comment by garrensmith** [comment]
The pouchdb-find test passes. Not sure why the other fail. I'm +1 on this it look great.

**Comment by garrensmith** [comment]
Wait, it seems the pouchdb-find is failing.

**Comment by nolanlawson** [comment]
Yeah the "select is null" test is failing. Apparently my `npm link` fix didn't work. I need to debug.

**Comment by nolanlawson** [comment]
OK that should do it. express-pouchdb needed to be linked back to the monorepo too.

**Comment by garrensmith** [comment]
Nice work

All misspelling thanks to my iPhone.




On Tue, Mar 21, 2017 at 5:09 PM +0200, "Nolan Lawson" <notifications@github.com> wrote:












OK that should do it. express-pouchdb needed to be linked back to the monorepo too.

**Pull request merged**
