### PR TITLE
(#4265) - Add <input type=file> example to the attachments guide

### PR DESCRIPTION
**Pull request by ntwcklng**

### CODE REVIEW

**Comment by nolanlawson** [comment]
Looks great, thanks a lot! I made some minor copyedits and squash-merged your commit as ab55df4a118a06e8aa023a938a70abfcac2ee243 and bc04a14ae4d916e38d61f92b74122d97107e2a44. Publishing now!

**Comment by Charlotteis** [comment]
Nice one @ntwcklng! Thank you :)

**Comment by nickcolley** [comment]
Thanks @ntwcklng :)

**Comment by ntwcklng** [comment]
Cool, thanks! :tada:

**Pull request closed without merging**
