### PR TITLE
(#3179) - fix live replication of conflicts

### PR DESCRIPTION
**Pull request by nolanlawson**
This was one of those one-line bugfixes that
took me a few hours to figure out. :P

The tests fail before the fix but succeed after.
Pretty straightforward.

### CODE REVIEW

**Comment by nolanlawson** [comment]
So here's what happened:

We weren't correctly passing `style=all_docs` to the changes API for *live* changes (non-live changes were fine). This meant that, in the case of non-winning revisions like e.g. deleted conflicts, the revs weren't being mentioned in the `changes` list on the emitted `change` object because hey, they weren't the winning revision, and it wasn't `style=all_docs`, so non-winning leafs could be omitted. So the target database would never get notified about later non-winning revisions.

In those tests, there were 8 variations (live/nonlive, plus all the local/http pairs), but only 4 were failing: non-winning and local-originating (i.e. local-local and local-http).

**Comment by nolanlawson** [comment]
increased the timeout to 10 seconds because it seemed faily in travis

**Comment by nolanlawson** [comment]
The tests are faily. @daleharvey do you have any suggestions? It all works fine locally; can't figure out how to fix this without `setTimeout`... :/

**Comment by daleharvey** [comment]
https://github.com/pouchdb/pouchdb/pull/3511/files#diff-070382d6862d30174d29271e33abbfeeR180 looks suspect, cancelling replication isnt synchronous, needs to wait for a `.on('complete'` before returning from the test

**Comment by nolanlawson** [comment]
third attempt

**Comment by nolanlawson** [comment]
green! and not faily at all; it only failed in one test (couchdb-master), so I re-ran it.

**Comment by daleharvey** [comment]
That is a good amount of tests for a 1 line patch :) we need more tests for this stuff so this is awesome, thanks

https://github.com/pouchdb/pouchdb/commit/572539869b1595e579c53c71a7f55b0cfa27cdb2

**Pull request closed without merging**
