### PR TITLE
(#3850) - blog post about promises

### PR DESCRIPTION
**Pull request by nolanlawson**
If everybody's cool with this post, I'd like to publish
it next Monday morning EST. Hence the date. :)

### CODE REVIEW

**Comment by nolanlawson** [comment]
Here's a built version so you don't have to build the website yourself: https://nolanlawson.s3.amazonaws.com/pouchdb/www/20150516/index.html

**Comment by nickcolley** [comment]
Great post!

One note: felt the title and opening intro was a bit link baity and negative, think it's important to have positive messaging as it doesn't exclude anyone.

Another example is the usage of 'Rookie mistake'.

So maybe something along the lines of "Mastering Promises With This One Weird Trick" (I'm joking but hopefully you see my point)

Generally I think positive tone in copy helps the audience feels empowered and confident.

**Comment by nolanlawson** [comment]
I agree. I want to largely redo the title and intro paragraph. Clickbait felt good for a moment, but it nags at me the more I think about it.

"Rookie mistake" is okay in my mind; it's encouraging, like, "you're a rookie now, but you'll be a pro soon." What would you suggest?

**Comment by nolanlawson** [comment]
@nickcolley Thanks a lot, your advice really helped. I went through and basically scrapped the title and the first few paragraphs. You're right that it's more important to be supportive and try to identify how people are going to be empowered by reading my post.

I squashed everything, but you can see the diff here: https://github.com/pouchdb/pouchdb/commit/bf596b92cf7424a0ef4b15a48ce85edd2fce7ca7

**Comment by daleharvey** [comment]
Awesome, I mentioned on IRC but I was going to mirror what @nickcolley said as well, I think the content of the post was awesome but the presentation negative. The revision reads well and is super useful. thanks loads, :+1: for publishing when you want to

**Comment by nolanlawson** [comment]
9cd9656f42f89a3279eac063d6ec77064b3bba7e, publishing now

**Comment by nolanlawson** [comment]
Published!

**Comment by nickcolley** [comment]
Thanks for this @nolanlawson :+1:

**Pull request closed without merging**
