### PR TITLE
(#3435) - Remove duplicate `writeDocs` definition.

### PR DESCRIPTION
**Pull request by neojski**
Kind of the other way round: removing custom `writeDocs` doing the same as that one from utils.

### CODE REVIEW

**Comment by nolanlawson** [comment]
+1 when green

**Comment by nolanlawson** [comment]
also welcome back @neojski :)

**Comment by neojski** [comment]
Are these legitimate failures?

**Comment by nolanlawson** [comment]
Nah, couch-master is failing as of a few days ago (https://github.com/pouchdb/pouchdb/issues/3721). I'd be happy to start accepting pull requests without those tests succeeding.

**Comment by nolanlawson** [comment]
e3a3d2f43cb01cb8c47a57a1c2e2aca21648885a

**Pull request closed without merging**
