### PR TITLE
(#3577) - edit intro docs

### PR DESCRIPTION
**Pull request by nolanlawson**
The "Learn" page is probably the first place where
users will land after the home page, and I wanted to
clean it up and update the description a bit.

As for the API, I cleaned up some small inconsistencies
and added a longer intro section on promises/callbacks.
At some point, I would like to go in there and just remove
the callback examples entirely. I think we should deprecate
the callback API.

### CODE REVIEW

**Comment by nolanlawson** [comment]
New Learn page:

screenshot 2015-02-25 23 23 21


New API page:

screenshot 2015-02-25 23 23 34

**Comment by nickcolley** [comment]
Need some time to have a proper review but I also think having both methods documented sporadically is very confusing. It's led to using *both* in a project I've seen which is not great.

I started investigating having a way to swap the docs between  promises and callbacks but maybe it's worth just keeping it simple and only exposing one way.

**Comment by nolanlawson** [comment]
I'd be fine with having a little switcher between the two, assuming promises was the default.

**Comment by nolanlawson** [comment]
@nickcolley I think a design like [this one](http://developer.couchbase.com/mobile/develop/guides/couchbase-lite/native-api/document/index.html#creating) might be nice. I.e. where they have a tab switcher between Objective-C, Swift, Java, etc., we could have a switcher between promises and callbacks.

**Comment by nickcolley** [comment]
@nolanlawson let me see what I can do

**Comment by nickcolley** [comment]
https://github.com/nickcolley/pouchdb/tree/xxxx-api-promise-callback-magic

I'm using javascript to replace the static blocks, the api document is really gnarly at the moment though.
Thinking we could split it up into sections or something? Jekyll only goes so far I guess...

**Comment by nolanlawson** [comment]
That is MARVELOUS. And yes, we probably should break it up. How would you recommend we do that?

**Comment by nolanlawson** [comment]
BTW I'm happy to start working on updating the whole API page. This is great stuff.

**Comment by nickcolley** [comment]
Might be able to separate the api and concat them together somehow.

**Comment by nolanlawson** [comment]
@nickcolley for the time being, don't worry. I am happy to rewrite the big API page to incorporate this stuff. :)

**Comment by nolanlawson** [comment]
Since editing the API seems like a much bigger undertaking, I removed the API changes and kept only the "intro" changes (learn.md and adapters.md). I'll move the API changes to a new PR.

**Comment by daleharvey** [comment]
This wasnt included in https://github.com/pouchdb/pouchdb/pull/3584 right and needs rebased, apologies

**Comment by nolanlawson** [comment]
I'm not seeing any merge conflicts. Okay to just merge to master?

**Comment by nolanlawson** [comment]
Rebased.

**Comment by daleharvey** [comment]
Yup looks good - https://github.com/pouchdb/pouchdb/commit/2e60ea335fd3e11ad273fcd88e24c27ef443de5d

**Pull request closed without merging**
