### PR TITLE
Add md5sum wikipedia link

### PR DESCRIPTION
**Pull request by RichardLitt**

### CODE REVIEW

**Comment by daleharvey** [comment]
@RichardLitt this is markdown, so [MD5 sum](http://en.wikipedia.org/wiki/Md5sum) is a bit better than manually creating the HTML, do you mind ammending? otherwies looks good thanks a lot

**Comment by RichardLitt** [comment]
Changed. The wiki link above for MIME types should also be changed, as it uses <a> tags and I figured that was some sort of weird style thing for this doc.

**Comment by Kiwiroo** [comment]
'


Sent from my Samsung Galaxy S®4

-------- Original message --------

**Comment by nolanlawson** [comment]
@RichardLitt long story, but that's because our alert snippets only accept HTML, not markdown. anyway this looks good to me, thanks!

**Comment by nolanlawson** [comment]
4355f3404d73a905ddd496f03630da4b8a373c05

**Pull request closed without merging**
