### PR TITLE
(#2824) - Get console from running saucelabs failures

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by nickcolley** [comment]
What's the best way to check this is working on Travis?

**Comment by daleharvey** [comment]
If you put up a build that does a console.log somewhere inside the test run you can see if the test run fails, I was using it to debug https://github.com/pouchdb/pouchdb/pull/4747 so its definitely working.

I think I will amend this to also add the logs to passing commits, seems like it would also be useful

**Comment by nolanlawson** [comment]
This is a great idea. :+1: from me, wonder why we didn't do it earlier.

**Comment by daleharvey** [comment]
Awesome cheers - https://github.com/pouchdb/pouchdb/commit/b933b9847c1855e65d26e8bca9fb9c250e853b5b

**Pull request closed without merging**
