### PR TITLE
(#3095) - Use selenium-standalone to manage selenium

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by nolanlawson** [comment]
If this works, I would love to start fixing all the plugins as well. It's a PITA to remove the selenium jar just for the benefit of bower users.

**Comment by daleharvey** [comment]
@vvo any idea about whats happening here? locally this is running fine, but dying in travis

**Comment by daleharvey** [comment]
Looks like its the same version issue I was talking about earlier, assumed if I did `export SELENIUM_VERSION=2.42.0` it would apply to all scripts, but doesnt seem so

**Comment by nolanlawson** [comment]
Gonna play it safe and wait for a green in iphone+ie as well. Restarting those jobs.

**Comment by daleharvey** [comment]
So iphone is faily randomly depending on what time of the day it is, it doesnt go through this at all as it uses the sauceClient and not the selenium server (https://github.com/pouchdb/pouchdb/blob/master/bin/test-browser.js#L206)

Its a fairly consistent error these days (security exception) so I will take a look at getting it back green soon, but I dont think it needs to block this

**Comment by nolanlawson** [comment]
IE is green, so fair enough. +1

I'm mostly just paranoid about IE failures. iPhone failures are usually also caught by Phantom or Safari.

**Comment by daleharvey** [comment]
Great thanks - https://github.com/pouchdb/pouchdb/commit/bbf577d369763608f42d6eb8a7e67f2c79e0eb04

**Pull request closed without merging**
