### PR TITLE
Clarify code & info about Persistent Queries

### PR DESCRIPTION
**Pull request by BigBlueHat**
Just a few things that tripped me up that today. Hopefully this'll help others. :smiley: :

### CODE REVIEW

**Comment by nolanlawson** [comment]
I think that for veteran users of CouchDB, things like `mydesigndocname/myviewname` are obvious, but for new users I think it's just too overwhelming. That's why I made it so that `foo/foo` is equivalent to `foo`.

Can you think of a way that would have made it easier for you to understand without introducing the `/`?

**Comment by daleharvey** [comment]
I actually think the opposite, the fact that `foo` refers to the view `foo` inside the design doc `_design/foo` is somewhat a big of magic, whereas `ddocname/viewname` is consistent and more explicit. I mean neither are a particular nice api, but I think it will make things clearer to document the plain old dumb api as opposed to the slightly magic one

**Comment by daleharvey** [comment]
Also ignore the errors, if you rebase they will be fixed

**Comment by nolanlawson** [comment]
Still disagree; newbies don't know what design docs are, don't care, and just want the shortest path to making an "index."

But yeah, that'll be better fixed by the indexes plugin ([making progress, btw](https://github.com/nolanlawson/pouchdb-indexes)). So sure, +1

**Comment by nolanlawson** [comment]
207cb4e7b9420c9b094eadaa8bc75dd5ca8e39dd

**Pull request closed without merging**
