### PR TITLE
ci: remove test retries, skip flaky tests

### PR DESCRIPTION
**Pull request by alxndrsn**

### CODE REVIEW

**Comment by alxndrsn** [comment]
This PR surfaces less frequent test failures/flake:

### [`browser-adapter (firefox, indexeddb, npm test`)](https://github.com/pouchdb/pouchdb/actions/runs/6278057680/job/17051100014?pr=8757#logs)

```
  1067 passing (2m)
  27 pending
  1 failing

  1) test.sync.js-http-http 5007 sync 2 databases:
     Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  finished@utils-bundle.js:15381:7
  [27]</</</_setup/this.destroy</r/<@http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:59481
  [27]</</</vn/r._destroy@http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:111626
  async*r@http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:59403
  [27]</</</_setup/this.destroy<@http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:59521
  [27]</</</w/<@http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:35875
  [27]</</</b/</i<@http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:35223
  [27]</</</b/<@http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:35133
  [27]</</</w/</</<@http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:35963
  execute@http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:61523
  ready@http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:61604
  [27]</</</_setup/<@http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:63607
  [27]</</</vn/<@http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:103785
  [3]</p.prototype.run@http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:7477
  l@http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:7207
  VoidFunction*[6]</</</n.install/<@http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:8732
  [3]</t.exports@http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:7761
  vn@http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:103771
  _setup@http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:63237
  [27]</</</Ye<@http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:63672
  n@http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:61756
  [29]</</</testUtils.cleanup/<@utils-bundle.js:15386:5
  [29]</</</testUtils.cleanup@utils-bundle.js:15385:7
  @test.sync.js:21:17
```

### [`couchdb-browser (3.1, firefox, TYPE=mapreduce ADAPTERS=http npm test)`](https://github.com/pouchdb/pouchdb/actions/runs/6278057680/job/17051102746?pr=8757#logs)

```
  198 passing (34s)
  1 failing

  1) test.persisted.js should query correctly with stale update_after:
     query() returned immediately: expected [ Array(5) ] to have a length of 0 but got 5
  AssertionError@http://127.0.0.1:8000/node_modules/chai/chai.js:5553:18
  [3]</module.exports/Assertion.prototype.assert@http://127.0.0.1:8000/node_modules/chai/chai.js:206:13
  assertLength@http://127.0.0.1:8000/node_modules/chai/chai.js:1334:10
  doAsserterAsyncAndAddThen@http://127.0.0.1:8000/node_modules/chai-as-promised/lib/chai-as-promised.js:296:33
  chaiAsPromised/</</<@http://127.0.0.1:8000/node_modules/chai-as-promised/lib/chai-as-promised.js:274:54
  [25]</module.exports/chainableBehavior.method@http://127.0.0.1:8000/node_modules/chai/chai.js:5287:34
  assert@http://127.0.0.1:8000/node_modules/chai/chai.js:4121:49
  @test.persisted.js:377:30
  promise callback*@test.persisted.js:376:10
  ```
  
  
### [`couchdb-nodejs (2.3, 14, npm test)`](https://github.com/pouchdb/pouchdb/actions/runs/6278057680/job/17051096087?pr=8757#logs)` 

```
  937 passing (1m)
  13 pending
  1 failing

  1) test.issue915.js Put a file in the db, then destroy it:
     Error: ENOENT: no such file or directory, open './tmp/_pouch_veryimportantfiles/something'
```

**Comment by alxndrsn** [comment]
Skip of test.retry/destroyed event listener leak opened as a separate PR at https://github.com/pouchdb/pouchdb/pull/8765

**Comment by alxndrsn** [comment]
Here's another one:

```
   1) test.issue3179.js-local-http #3179 conflicts synced, non-live sync:
     AssertionError: conflicts expected, but none were found: expected undefined to exist
      at doAsserterAsyncAndAddThen (node_modules/chai-as-promised/lib/chai-as-promised.js:296:33)
      at Assertion.<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:286:25)
      at Assertion.get (node_modules/chai/lib/chai/utils/overwriteProperty.js:50:37)
      at Object.should.exist (node_modules/chai/lib/chai/interface/should.js:126:34)
      at tests/integration/test.issue3179.js:88:18
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
  ```

**Review by garethbowen — COMMENTED** [review]
Do you think this will lead to more builds passing or fewer?

**Comment by alxndrsn** [comment]
> Do you think this will lead to more builds passing or fewer?

More.

**Pull request closed without merging**
