### PR TITLE
(#4193) - migrate to container-based Travis

### PR DESCRIPTION
**Pull request by nolanlawson**
CSG will still be broken in this PR because we
don't have sudo anymore, but I'm just testing
to see if this will work.

### CODE REVIEW

**Comment by nolanlawson** [comment]
So this actually seems very close to passing, but I'm not sure what benefit it's giving us. It doesn't seem much faster than the old system.

**Comment by nolanlawson** [comment]
OK, actually there do seem to be big benefits [per this doc](http://docs.travis-ci.com/user/migrating-from-legacy/) (e.g. additional cores/RAM), and especially if we start [caching node_modules](http://blog.travis-ci.com/2013-12-05-speed-up-your-builds-cache-your-dependencies/)

**Comment by nolanlawson** [comment]
Weird, looks like SpiderMonkey isn't being compiled correctly:

    /home/travis/couchdb/src/couch/priv/couch_js/http.c:18:19: fatal error: jsapi.h: No such file or directory

I thought this would be fixed by adding `g++` to the apt sources list, but apparent. I know I've run into this like a million times with Couch, but I can never remember what the fix is. :/

**Comment by nolanlawson** [comment]
Since this improves the build time so much, and since Couch master is in the allowed failures anyway, I would suggest we just merge and then open another issue to fix Couch master. Same for CSG; it will also be permafail until we fix the sudo issues.

**Comment by daleharvey** [comment]
I can live with that, hopefully someone else is working on couch / travis integration as well so maybe ping them in the new issue, :+1:

**Comment by nolanlawson** [comment]
9d6b611c6467944c5de2cad668642e35fa4109d3

**Pull request closed without merging**
