### PR TITLE
Added short explanation on updating documents

### PR DESCRIPTION
**Pull request by lybekk**
Issue #8159
/guides/updating-deleting.html does not directly describe
how to update documents. Added a short explanation with
links to relevant sources.

### CODE REVIEW

**Comment by daleharvey** [comment]
Adding this section looks helpful, but I would be hesistant to add without a code example there as is in the deleted section, any chance you can add one? Thanks

**Review by daleharvey — CHANGES_REQUESTED** [review]
Meant to flag as requesting changes to keep track

**Comment by lybekk** [comment]
Will do :) Thanks!

**Comment by daleharvey** [comment]
Closing out for now but feel free to reopen with the code block, cheers

**Pull request closed without merging**
