### PR TITLE
WIP - Add ability to intercept/override ajax

### PR DESCRIPTION
**Pull request by daleharvey**
This isnt finished, but enough for feedback, so `req` probably isnt the best name for the option here but cant think of anything better of the top of my head.

Also if anyone who wants to use this, @martinfridrich, @DanielMaly or anyone else could take a look at this and see if it satisfies their requirements it would be awesome

### CODE REVIEW

**Comment by daleharvey** [comment]
Getting closer here, converting the tests that previously overrode `db._ajax` to use the modifier. Theres an issue I need to look at ensuring that we can cancel modified requests (and possibly that they can cancel themselves?)

**Comment by cdaringe** [comment]
@daleharvey, nice start!  looks great.  pedantically, i'd prefer `(ajax, opts)` vs `(opts, ajax)`, as `ajax` seems primary `opts` seem secondary to me... but nbd.  i'm borderline ashamed for even commenting about it :)

**Comment by daleharvey** [comment]
So yeh I have thought about that a bit, `(ajax, opts)` follows our style a little more because in general opts are optional extras, and in terms of an api its much better to have `(required, optional)` however that the exact reason that they are this way round. There are situations where you might use neither (`Promise.reject`), situations where you would use `opts` but not `ajax` using an alternative transport, situations where you would use both `return opts(ajax)`, but almost never a situation where you use `ajax` but not `opts`

**Comment by daleharvey** [comment]
kicking the travis tyres

**Comment by DanielMaly** [comment]
This is awesome! I have implemented my functionality using db._ajax in the end, will that break in the near future? Anyway, as long as the `opts` object contains the method, URL, headers, body and content-type, I will be happy.

**Comment by daleharvey** [comment]
yup `db._ajax` doesnt work with this patch, but yes `opts` contains all the data that is used to make the request

**Comment by daleharvey** [comment]
And for those following along, https://github.com/pouchdb/pouchdb/pull/5763/files#diff-f8ba360f868e295f81e2520b3db3986aR193 is probably the best place to get familiar with what the new functionality looks like, this is passing locally so going to see what the test run looks like but aside from that this is mostly finished aside from the docs

**Comment by martinfridrich** [comment]
Hi, sorry for late response. I try to test this but I've got infinite loop when try with `pouchdb-server 1.2.0` and doc isn't synced.

```
var p = new PouchDB("local_db");

var rep = PouchDB.replicate(p, 'http://127.0.0.1:8080/test', {
  live: true,
  retry: true,
  req: function (opts, ajax) {
    return ajax(opts).then(function (res) {
      res.customfield = 'foo';
      return res;
    });
  }
}).on('change', function (info) {
  console.log("changes");
  console.log(info);
  console.log("------------------------------");
}).on('paused', function (err) {
  console.log("paused");
  if (err) {
    console.log(err);
    console.log(err.stack);
  }
  console.log("------------------------------");
}).on('active', function () {
  console.log("active");
  console.log("------------------------------");
}).on('denied', function (err) {
  console.log("denied");
  console.log("------------------------------");
}).on('complete', function (info) {
  console.log("complete");
  console.log(info);
  console.log("------------------------------");
}).on('error', function (err) {
  console.log("error");
  console.log(err);
  console.log("------------------------------");
});
```
I've got this error in browser console after add doc(both `put/post`) 
```
TypeError: Cannot read property 'length' of undefined
    at Array.filter (native)
```

log from poucdb-server console
```
[info] GET / 304 - 127.0.0.1
[info] GET /test/_local/MwZiWRzmgJa21kuH14LmCg%3D%3D? 404 - 127.0.0.1
[info] POST /test/_revs_diff 200 - 127.0.0.1
```
and this loop forever

Everything is working ok when I comment `req:function...` from db options.

thanks

**Comment by martinfridrich** [comment]
ok, problem was that function also modify response with revisions and then pouch chrash in function `getRevisionOneDocs()`

**Comment by daleharvey** [comment]
Yeh I have seen that before, when the modifier function crashes it can be hard to determine what the problem is, it may be an idea to add some handling in there to make sure crashes are visible

**Comment by daleharvey** [comment]
Ok this should be now good to go :) I went with `opts.request` as `typeof opts.ajax === 'function'` was going to prevent people from specifying both a request and `opts.ajax.cache` for example

**Comment by cdaringe** [comment]
woo hooooooo @swashcap :eyes:

**Comment by jsdevel** [comment]
@daleharvey would it be possible to add a handler for `response`?  If we had that, then we could probably work around #5607.

**Comment by daleharvey** [comment]
@jsdevel That is part of this, you can handle and modify responses @ https://github.com/pouchdb/pouchdb/pull/5763/files#diff-f8ba360f868e295f81e2520b3db3986aR225 or do you mean something different?

**Comment by daleharvey** [comment]
Actually thinking about this I may want to hold off on this a tiny bit, the `ajax` implementation looks a lot like fetch but differs in quite a few ways, we use errors for `4XX` and some params are not identical. I think it would be far easier to understand if `ajax` was `fetch`

**Comment by nolanlawson** [comment]
I agree with Dale; now that we're moving towards "prefer `fetch()`, fall back to `XMLHttpRequest()`, any ajax-related hooks should really apply to `fetch()` rather than XHR. I consider this blocked by #5835  and unfortunately needing largely a rewrite to be approved; sorry about that.

**Pull request closed without merging**
