### PR TITLE
(#3571) - blog post about UI state

### PR DESCRIPTION
**Pull request by nolanlawson**
This came up recently as a question on IRC, and I thought
it was interesting enough to turn into a blog post. It's
been awhile since we had a non-release blog post. :)

### CODE REVIEW

**Comment by nickcolley** [comment]
How about we inline your toy at the end of the post since we have Pouchdb global? :dancer:

**Comment by nolanlawson** [comment]
I like the way you're thinking, but let's keep it simple for now. :)

**Comment by nolanlawson** [comment]
At some point in the future I would like a consistent way to inline code samples (maybe a jekyll `include`?) Then we should definitely update this post to do it inline.

**Comment by nickcolley** [comment]
I'm working on that currently, based on the demo @ http://nck.im/try/

**Comment by daleharvey** [comment]
This is awesome, +1 to release when you think is good for you

**Comment by nolanlawson** [comment]
I'll do it right now; don't want to steal the limelight from the Monday release. :)

**Comment by nolanlawson** [comment]
0a523ed98c545232b761ba1203c57b6ddd393fb8

**Pull request closed without merging**
