### PR TITLE
(#3945) - Use seedrandom to generate deterministic fuzzy tests

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by daleharvey** [comment]
@davidbau @tohagan So this works perfectly in the browser, not so much however in node however, https://github.com/pouchdb/pouchdb/pull/3997/files#diff-6bfead107e6dd15398d98c576e64ecaeR6 is the code that is ran in node, any ideas?

@nolanlawson / anyone who fancies reviewing, I can actually use this now and am finding / able to reproduce bugs in the browser  (try http://127.0.0.1:8000/tests/fuzzy/?seed=hello), so I think its fine to merge now and follow up fixing node

**Comment by tohagan** [comment]
@daleharvey - I've not yet had a chance to checkout and run your code but would like to. Are you seeing a different random sequence in Node to browsers?

**Comment by tohagan** [comment]
If your UUIDs in PouchDb are being generated to include time stamp values
you might then get different (random) winners in update collisions.
You may find that tests sometimes pass and sometimes fail.
Fix this by creating a test only shim for your UUID function so it avoid
using the clock and on uses PRNG so it's predictable.
Your current code is replacing the Math.random() - That's fine for use
*inside* PouchDb but you want to use a different PRNG seed and sequence for
the generated unit tests.
To do this just select a different PRNG function from the library.
   https://github.com/davidbau/seedrandom/tree/released/lib

I'd also write one random number to console for each sequence at the start.

Tony.





On Mon, Jun 22, 2015 at 8:45 AM, Dale Harvey <notifications@github.com>
wrote:

> @davidbau <https://github.com/davidbau> @tohagan
> <https://github.com/tohagan> So this works perfectly in the browser, not
> so much however in node however,
> https://github.com/pouchdb/pouchdb/pull/3997/files#diff-6bfead107e6dd15398d98c576e64ecaeR6
> is the code that is ran in node, any ideas?
>
> @nolanlawson <https://github.com/nolanlawson> / anyone who fancies
> reviewing, I can actually use this now and am finding / able to reproduce
> bugs in the browser (try http://127.0.0.1:8000/tests/fuzzy/?seed=hello),
> so I think its fine to merge now and follow up fixing node
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pouchdb/pouchdb/pull/3997#issuecomment-113965512>.
>



-- 
Email: tony@ohagan.name

**Comment by nolanlawson** [comment]
+1

**Comment by daleharvey** [comment]
Cheers, merged in https://github.com/pouchdb/pouchdb/commit/0e304e515b86e7730a0f87a0e77201bcb25e7586

**Pull request closed without merging**
