### PR TITLE
(#5962) - fix broken verify-bundle-size.sh script

### PR DESCRIPTION
**Pull request by nolanlawson**
Will probably fail due to #5973 but here's the PR anyway, can rebase later...

### CODE REVIEW

**Comment by nolanlawson** [comment]
Also the only test that matters is the "verify build" test which doesn't require Java, so we can just ignore the other failures

**Comment by nolanlawson** [comment]
Went ahead and rebased on thing to workaround travis bug

**Comment by nolanlawson** [comment]
de-rebased because the Travis bug seems fixed

**Comment by daleharvey** [comment]
How was this not failing when we stopped minifying in travis?

**Comment by nolanlawson** [comment]
The size was 0 and therefore it passed.

**Comment by daleharvey** [comment]
Ah duh yeh, could you put a check in there for >1 to make sure that doesnt happen again?

**Comment by nolanlawson** [comment]
Sure thing!

**Comment by nolanlawson** [comment]
9abef3a162f9a117497aaca9c3273d20cf7bb23c

**Pull request closed without merging**
