### PR TITLE
(#3806) - 3.5.0 release blog post

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by daleharvey** [comment]
I figured fetch support made this a 3.5.0, if people think its 3.4.1 though I woud be find changing

**Comment by nolanlawson** [comment]
it's definitely a 3.5.0 because of the extras API and the browserifiability of the adapter plugins

**Comment by nickcolley** [comment]
#votehype

**Comment by ctlacko** [comment]
+1 where do we vote?

**Comment by daleharvey** [comment]
Done https://github.com/pouchdb/pouchdb/commit/88336ad236926bffce41b40c7566febade6ef7d0 cheers all

**Pull request closed without merging**
