### PR TITLE
Combine readOnlySource and writeSourceCheckpoint

### PR DESCRIPTION
**Pull request by alxndrsn**

### CODE REVIEW

**Comment by alxndrsn** [comment]
The build is failing for the following reasons:

# `COMMAND=report-coverage`
https://travis-ci.org/pouchdb/pouchdb/jobs/272432098
```
  1) test.read_only_replication.js Test checkpointer handles error codes:
     TypeError: Cannot set property 'writeSourceCheckpoint' of undefined
      at packages/node_modules/pouchdb-for-coverage/lib/index.js:9:476120
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

# `COMMAND=test-component`
https://travis-ci.org/pouchdb/pouchdb/jobs/272432096
```
  1) test.read_only_replication.js Test checkpointer handles error codes:
     TypeError: Cannot set property 'writeSourceCheckpoint' of undefined
      at packages/node_modules/pouchdb-for-coverage/lib/index.js:9277:45
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

I'll get this fixed.

**Comment by alxndrsn** [comment]
Cross-referencing the three builds at https://travis-ci.org/pouchdb/pouchdb/builds/272432059, https://travis-ci.org/pouchdb/pouchdb/builds/274608455, https://travis-ci.org/pouchdb/pouchdb/builds/275132176, the only test which is consistently failing is for code coverage.

Coverage summary:
```
=============================== Coverage summary ===============================
[32;1mStatements   : 99.98% ( 5782/5783 ), 165 ignored[0m
[32;1mBranches     : 98.12% ( 2968/3025 ), 149 ignored[0m
[32;1mFunctions    : 100% ( 1097/1097 ), 22 ignored[0m
[32;1mLines        : 99.98% ( 5777/5778 )[0m
================================================================================
ERROR: Coverage for lines (99.98%) does not meet global threshold (100%)
```

However, due to https://github.com/pouchdb/pouchdb/issues/6740, I can't generate a coverage report locally to actually see what isn't covered.

And on travis, the reports appear to be inaccessible:
```
=============================================================================
Writing coverage object [/home/travis/build/pouchdb/pouchdb/coverage/coverage.json]
Writing coverage reports at [/home/travis/build/pouchdb/pouchdb/coverage]
=============================================================================
```

**Comment by daleharvey** [comment]
ok I will run this locally and see whats up with the tests

**Comment by daleharvey** [comment]
@alxndrsn we have had some updates to the tests and your other patch landed here so could you rebase this and land if all good, otherwise I will take a look at whats up with the failures, cheers

**Comment by alxndrsn** [comment]
👍 will have a go at rebasing

**Comment by alxndrsn** [comment]
@daleharvey Travis says this is working now :¬)

**Pull request merged**
