### PR TITLE
(#4903) - Escape unicode in auth header

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by daleharvey** [comment]
@unpete Could you test this and confirm that it is the correct fix? Thanks

**Comment by unpete** [comment]
Ok, this fix corrects a problem with the authorization

**Comment by daleharvey** [comment]
Awesome thanks, will take as a :+1: but leave it for a while before merging to lets others to take a look

**Comment by daleharvey** [comment]
And merged in https://github.com/pouchdb/pouchdb/commit/e45e7a04567025085a92a6ad0d95d59d68b84321, thanks

**Pull request closed without merging**
