### PR TITLE
(#3932) - add a sanity test for attach replication

### PR DESCRIPTION
**Pull request by nolanlawson**
Adds a test to make sure attachments can replicate.

### CODE REVIEW

**Comment by nolanlawson** [comment]
@ermouth I still can't reproduce any of these bugs, but I'm trying.

**Comment by daleharvey** [comment]
Test looks good, cheers - https://github.com/pouchdb/pouchdb/commit/205f4a32585c5bbf05057c52b0a0bc526aba0f93

**Comment by ermouth** [comment]
@nolanlawson i noticed FF shows there are unfinished transactions on tab reload, is it normal?

**Comment by daleharvey** [comment]
That is a bug in firefox - https://bugzilla.mozilla.org/show_bug.cgi?id=1147942

**Pull request closed without merging**
