### PR TITLE
(#6864) fix missing return statements on allDocs indexeddb adapter

### LINKED ISSUE #6864: Missing return on allDocs of indexeddb adapter
In @dharders PR there is a return missing in the [allDocs implementation of indexeddb adapter](https://github.com/pouchdb/pouchdb/pull/6833/files#diff-dbb317186915d268eca5f85f5456363dR49). When running the integration tests in chrome I noticed this. It will throw this error `once called more than once`, because callback is called multiple times on allDocs

### PR DESCRIPTION
**Pull request by dharders**
Closes #6864 

/cc @nename0

### CODE REVIEW

**Comment by dharders** [comment]
Hmmm, the test `CLIENT=selenium:firefox:47.0.2 COMMAND=test-webpack` failed 1st run at a random test, which usually solves itself with the normal travis retry attempt logic, but weirdly the subsequent builds failed on retry 2 and 3 before even getting to run the tests. 

Unsure if this is a result of the latest `run-tests.sh` script update merge (see [pull/6865#issuecomment-346929550](https://github.com/pouchdb/pouchdb/pull/6865#issuecomment-346929550)) or another travis issue altogether.

**Comment by nename0** [comment]
I would not trust travis to much, it has been failing at random lately ([What's this?](https://travis-ci.org/pouchdb/pouchdb/jobs/306746236)) . You only changed pouchdb-next code so i would onlx look in the 28th build test, which passes for you. Also the test result are more or less meaningless until #6896 and #6870 are fixed.

**Comment by dharders** [comment]
@nename0 thanks for the explanation and thanks for addressing the travis issues. It will be great to get stability and confidence back from CI test results.

**Comment by nename0** [comment]
@dharders dale restarted the build job now it passes!

**Comment by daleharvey** [comment]
So basically, if a test you are touching turns red, or you make a change and there are 2+ of the same type of test (nodejs or browser) failing then its a good idea to take a look at the failure, otherwise yup its common for these to fail intermittently, they always will hoever they havent had much people look at them for a llong time so could do with some love

**Comment by dharders** [comment]
> if a test you are touching turns red ... and there are 2+ of the same type of test (nodejs or browser) failing ...  look at the failure

That's the conclusion that I had basically come to @daleharvey .

The confusing part was the failed **build** on retry 2 and 3, even though 1st build succeeded.

**Pull request merged**
