### PR TITLE
(#5653) - automatically determine dependencies at publish time

### PR DESCRIPTION
**Pull request by nolanlawson**
Problems:

1. We have to declare our dependencies in two places: top-level `package.json` and individual sub-package `package.json`s.
2. These can get out-of-date. For instance, I noticed `pull-stream` is no longer needed, and the core `pouchdb` package still had some dependencies from the legacy `extras` (e.g. `localstorage-down`).

Solution:

1. Script, `bin/update-dependencies.js` that runs during the release script
2. This script searches `lib/**/*.js` and finds all `require()` calls
3. Then it inserts `depenedencies` and `peerDependencies` with the correct verisons.

Thus we no longer need to declare dependencies inside of the sub-packages. I have manually inspected the output of `node bin/update-dependencies.js` and it looks good to me. I also removed `pull-stream` since it's no longer needed.

### CODE REVIEW

**Comment by nolanlawson** [comment]
yassss

screenshot 2016-09-08 09 40 21

**Comment by nolanlawson** [comment]
Cool, green!

I think with this fix we have a fully-satisfactory alternative to Lerna that addresses all the points in https://github.com/boennemann/alle. @garrensmith you might want to take a look at this and co-opt some of it for express-pouchdb.

**Comment by garrensmith** [comment]
Awesome. Will do. I've started on a new express-pouchdb monorepo design

All misspelling thanks to my iPhone.




On Fri, Sep 9, 2016 at 5:59 PM +0200, "Nolan Lawson" <notifications@github.com> wrote:












Cool, green!



I think with this fix we have a fully-satisfactory alternative to Lerna that addresses all the points in https://github.com/boennemann/alle. @garrensmith you might want to take a look at this and co-opt some of it for express-pouchdb.

**Comment by nolanlawson** [comment]
Rebased due to merge conflicts

**Comment by daleharvey** [comment]
This is awesome, 👍

**Pull request merged**
