### PR TITLE
removes obsolete Node v14 from CI testing

### PR DESCRIPTION
**Pull request by DougReeder**
The tests pass under Node 18 and 20 on MacOS 13, but under Node 18 on Debian, there is one failure, so adding Node 18 and 20 to CI will have to wait for a future PR.

  test.issue3179.js-local-http
    ✓ #3179 conflicts synced, non-live replication (178ms)
    1) #3179 conflicts synced, non-live sync

  924 passing (46s)
  17 pending
  1 failing

  1) test.issue3179.js-local-http #3179 conflicts synced, non-live sync:
     TypeError: Cannot read properties of undefined (reading '0')
      at tests/integration/test.issue3179.js:85:54
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### CODE REVIEW

**Review by lucidNTR — APPROVED** [review]
i see no downside to removing this, we should maybe add an node 18 target too, are you sure this is reproducibly failing not just part of the flakyness? (see https://github.com/pouchdb/pouchdb/issues/8692)

**Comment by SourceR85** [comment]
Node 18 and 20 should run fine.
I've played a little bit with them (see #8664)

**Comment by DougReeder** [comment]
If the tests are just flaky under Node 18 Debian, it's probably best to investigate before adding 18 to the CI.  IMNSHO, tests failing in CI should mean something.

**Comment by SourceR85** [comment]
@DougReeder the test-suite is flaky in every node version...
I don't expect some wonder, by just updating to another version 😉

**Review by alxndrsn — CHANGES_REQUESTED** [review]
Sadly this change breaks tests in new ways, e.g.

### [`pouchdb-server (firefox, TYPE=find PLUGINS=pouchdb-find ADAPTERS=http npm test)`](https://github.com/pouchdb/pouchdb/actions/runs/6347675908/job/17243056529#logs)

```
  1) test.ltgt.js $gt on nested field:

      expected 100 to equal 101
      + expected - actual

      -100
      +101
```

I think these should be addressed before merging.

**Comment by garethbowen** [comment]
This has been implemented in a separate PR.

**Pull request closed without merging**
