### PR TITLE
Use encodeDocId for PUT url.

### PR DESCRIPTION
**Pull request by jefbarn**
Fixes reverse proxy usage with pouch 6.0.

https://github.com/pouchdb/pouchdb/issues/5644

### CODE REVIEW

**Comment by willholley** [comment]
thanks - looks good to me!

**Comment by willholley** [comment]
@nolanlawson @daleharvey I was a bit overeager to merge this - the code patch is fine but the commit message doesn't match our convention. Are you able to patch it up?

**Comment by nolanlawson** [comment]
@willholley typically in these cases we just keep on rolling. We've made mistakes in the past; it's no big deal. Best not to force-push to master!

**Comment by nolanlawson** [comment]
Closing because this was merged as f17dd7ac7676967f9ba53c9d15b19a9b493c4e57

**Pull request closed without merging**
