### PR TITLE
WIP - Use latest firefox in travis

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by daleharvey** [comment]
Not strictly part of https://github.com/pouchdb/pouchdb/issues/5845 but cleaning up travis a little bit, this means we dont need to remember to update firefox version numbers (its currently out of date)

**Comment by daleharvey** [comment]
Looking at the test run, it seems we are using firefox 38 both before and after this change

**Comment by daleharvey** [comment]
actually want to see whats up with these versions before merging

**Comment by nolanlawson** [comment]
I was never able to figure out how to get latest firefox running in Travis. :( In many of my projects I swear I have the same config in two projects and yet I get different firefox versions.

**Pull request closed without merging**
