### PR TITLE
(#6266) - Allow regex, type and exists checks to use index when sorting

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by garrensmith** [comment]
This should fail against CouchDB. CouchDB doesn't allow that behaviour. But this brings up an interesting point. Some of the way we do sorting, querying in CouchDB has different constraints to pouchdb-find. For example sorting without an index could be possible in PouchDB but in CouchDB there isn't a way of doing that at the moment without causing an out of memory issue. I think it can be ok for PouchDB-find to deviate from the behaviour of CouchDB.

**Comment by daleharvey** [comment]
so not sure about the effect on the other tests, but all the newly added tests passed against couchdb without modification

**Comment by garrensmith** [comment]
Right. Ok. That is cool and a little suprising. My guess is then that uses the index for sorting and the filter in memory afterwards.

**Comment by daleharvey** [comment]
Yeh its looking like this patch breaks elsewhere, probably for the same reason you didnt expect it to work may just be an exception in couch, not looking to deviate from couch at the moment, mostly looking at pouchdb-find patchs so I can get familiar enough to work on native indexes

**Pull request closed without merging**
