### PR TITLE
(#3886) - Accessibility run through

### PR DESCRIPTION
**Pull request by nickcolley**

### CODE REVIEW

**Comment by daleharvey** [comment]
Huge +1, this is awesome, @nickcolley I think its based on an old version though, getting conflicts while trying to merge, can you rebase it please? Cheers

**Comment by daleharvey** [comment]
Actually just rebased it myself, was a whitespace change conflicting https://github.com/pouchdb/pouchdb/commit/e334860531dd43c9436a4c5c98e15a646bf9912e

**Comment by nickcolley** [comment]
Yeah not sure why my editor is changing so much whitespace, I'm on Linux, maybe I've got something configured differently..

**Comment by daleharvey** [comment]
Your editor is doing the right thing and trimming the extra whitespace in the files, you can likely configure it to trim only the whitespace on lines you edit, but its no bother that whitespace shouldnt be there anyway. I think I may add a linter to make sure we dont keep adding it by accident

**Pull request closed without merging**
