### PR TITLE
only test pouchdb-server

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by daleharvey** [comment]
Both https://github.com/pouchdb/pouchdb/pull/4217 and https://github.com/pouchdb/pouchdb/pull/4146 have bug fixes for pouchdb which are permafailing pouchdb-server running against firefox, all other servers passing

Fail doesnt seem to indicate much and neither of those patches have anything particularly weird for pouchdb-server

**Comment by nolanlawson** [comment]
Until #4232 is merged, we are still testing old versions of PouchDB Server. Likely we are running into bugs that were fixed a long time ago but are showing up again because npm is not resolving e.g. `0.6.0` to `0.9.0`.

That said, there is definitely still a bug in 0.9.0 that I can only repro in Firefox using Selenium (the `window.eval()` bug): https://github.com/pouchdb/pouchdb/pull/4217#issuecomment-136236786

**Comment by nolanlawson** [comment]
E.g. here is a Travis run where pouchdb-server is passing just fine. All I did was update express-pouchdb and pouchdb-server: https://travis-ci.org/pouchdb/pouchdb/builds/77936113

**Comment by daleharvey** [comment]
Thats the thing, its only failing on these patches, but yeh will test an update

**Comment by nolanlawson** [comment]
green in all tests, travis logs are here: https://travis-ci.org/pouchdb/pouchdb/builds/78126644

**Comment by daleharvey** [comment]
I am using this to debug the firefox failure, just wanted to start with a green build

**Comment by daleharvey** [comment]
So we cant do the trick where we `var ajax = PouchDB.utils.ajax` when we run the tests against pouchdb-server, I cant possibly think why right now, but that is the problem

**Comment by daleharvey** [comment]
Ok, got this figured out https://github.com/pouchdb/pouchdb/issues/4240

**Pull request closed without merging**
