### PR TITLE
Update UUID package

### PR DESCRIPTION
**Pull request by jpike88**

### CODE REVIEW

**Comment by garethbowen** [comment]
@jpike88 Thanks for submitting this! It looks like this has broken the tests - could you have another look please?

**Comment by jpike88** [comment]
@garethbowen I did the fix, and tests generally look good now, a couple are failing for some weird reason. Is that me?

**Comment by garethbowen** [comment]
@jpike88 Looks much better! I had a look and restarted one of the failing builds and the same tests failed. Can you have another look? It might help if you can run those tests locally.

**Comment by jpike88** [comment]
@garethbowen I have no idea how my tweak would have broken tests, the UUID library is all I upgraded, my tweaks have been minimal and specific.

https://travis-ci.org/github/pouchdb/pouchdb/jobs/684712122

This test is odd, and I can't reproduce it. My locally built pouchdb.min.js is 227 bytes, but that somehow fails in the linked job. Any idea why?

**Comment by daleharvey** [comment]
Somehow those changes are breaking minification, I can see the `pouchdb.js` is 355k which is bit of a bump in size, but `pouchdb.min.js` is not supposed to be 227 bytes, and is just

```
// PouchDB 7.0.0-prerelease
// 
// (c) 2012-2020 Dale Harvey and the PouchDB team
// PouchDB may be freely distributed under the Apache license, version 2.0.
// For all details and documentation:
// http://pouchdb.com
undefined
```

**Comment by daleharvey** [comment]
So when I run uglify manually I get 

```
~/src/pouchdb (master)$ ./node_modules/.bin/uglifyjs -mc < packages/node_modules/pouchdb/dist/pouchdb.find.js
Parse error at 0:1940,0
const v3 = (0, _v.default)('v3', 0x30, _md.default);
^
ERROR: Unexpected token: keyword «const»
    at JS_Parse_Error.get (eval at <anonymous> (/Users/dale/src/pouchdb/node_modules/uglify-js/tools/node.js:18:1), <anonymous>:71:23)
    at fatal (/Users/dale/src/pouchdb/node_modules/uglify-js/bin/uglifyjs:334:27)
    at run (/Users/dale/src/pouchdb/node_modules/uglify-js/bin/uglifyjs:277:9)
    at ReadStream.<anonymous> (/Users/dale/src/pouchdb/node_modules/uglify-js/bin/uglifyjs:200:9)
    at ReadStream.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1224:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

We are using uglify-js which only supports ES5, guessing uuid at some point started using ES6. I dont really undestand it all since we use ES6 imports, but thats why I filed https://github.com/pouchdb/pouchdb/issues/8097

**Comment by jshemas** [comment]
https://github.com/pouchdb/pouchdb/pull/8123 should fix the `uglify-js` issues with this PR.

**Comment by jpike88** [comment]
@daleharvey looks like it's green! eagerly awaiting release.

Thanks all

**Comment by daleharvey** [comment]
Awesome, I thought we were going to have an issue with es6 in ie11 but guess the magic in our build system does something about that, thanks

**Pull request merged**
