### PR TITLE
(#3543) - allow set Auth headers in replications

### PR DESCRIPTION
**Pull request by nolanlawson**
This fix seems obviously correct to me, and I can't think of a test for it since we don't use authentication in our test CouchDB. So I'd be fine with merging it as-is (assuming it's green).

### CODE REVIEW

**Comment by daleharvey** [comment]
We do some tests of recieving headers in test/components/, I would like to see us ensuring this via a test because the functionality can be confusing between whats supported / how it behaves, will try to take a look at how to get a nice test for this 

(it doesnt need to specifically test auth, just that the opts pass)

**Comment by daleharvey** [comment]
:+1: 

My new policy is to not block on things that make sense that dont have tests, if I want to make sure it doesnt break then i will write a test for it :)

**Comment by yaronyg** [comment]
@daleharvey Unless you have infinite time you can't write all those tests! I hate writing tests but it's one of the things that keeps PouchDB so damn reliable!

**Comment by nolanlawson** [comment]
2e995c080c7b273fe3215d0e4cd289ac9b9a9203

**Pull request closed without merging**
