### PR TITLE
(#4450) - Use js-extend for deep merging

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by daleharvey** [comment]
So the `js-extend` module is fairly minimal, it increases the total build slightly but seems to compress to the same .min size

```385848 12 Oct 15:22 pouchdb.js
151075 12 Oct 15:22 pouchdb.min.js

386520 12 Oct 15:25 pouchdb.js
151075 12 Oct 15:22 pouchdb.min.js```

**Comment by nolanlawson** [comment]
Do we still need a custom clone if we are using someone else's extend? Also I noticed you didn't delete `deps/extend.js`? Otherwise this seems reasonable to me.

**Comment by nolanlawson** [comment]
Actually wait, I remember now, our clone does some fancy stuff with `Date`s to fix those inconsistencies. So this makes sense.

**Comment by daleharvey** [comment]
Yup, although may be an idea to get our clone / extend based on the same code, will take a look, cheers, https://github.com/pouchdb/pouchdb/commit/6a10dff0734f29910eb296d4b3b777b9f1232357

**Pull request closed without merging**
