### PR TITLE
(#2154) - Test Android 4.4

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by daleharvey** [comment]
@filmaj Hey, do you have any idea whats up here? its an identical test run with android 4.4 vs 5.1, I can confirm locally that 4.4 emulator is passing 100%, it looks like the wrapper or whatever bootstraps the tests is different / broken in 4.4

**Comment by filmaj** [comment]
@daleharvey how can I tell what sauce job IDs / username these tests run under?

**Comment by daleharvey** [comment]
@filmaj hey

https://saucelabs.com/beta/tests/e6680d669ab04b7da0c0756307abb1ed/commands (6368.3)
https://saucelabs.com/beta/tests/5f1daf5c7fba46818eca117252f4a192/commands (6368.4)

are the 2 runs / ids, both under the username `pouchdb`

**Comment by daleharvey** [comment]
I just noticed the new logs, this is looking more useful to debug, @nolanlawson this is getting spit out as the manifest, is there anything obvious missing there? https://gist.github.com/daleharvey/0f6caa95eb98ecf2c18e

**Comment by nolanlawson** [comment]
@daleharvey Those all look normal to me. And in 4.4 there's nothing special you have to do to enable IndexedDB on the WebView; it should just work out of the box.

**Comment by daleharvey** [comment]
ok sweet, @filmaj is there anything else we can do to help debug this? it sounds like it is fairly definitely a bug on the saucelabs side, 5.1 is working fine as is everything locally

**Comment by nolanlawson** [comment]
For the record @daleharvey I opened a PR on selendroid, but after a lot of back-and-forth I finally realized that I was in the wrong repo. I never followed up, so maybe the fix could be applied elsewhere: https://github.com/selendroid/selendroid/pull/798

**Comment by filmaj** [comment]
I see some interesting logs in the logcat (hit the Logs dropdown -> logcat log gives you system + application log entries directly off the device / emulator).

This is definitely an issue with Selendroid's AndroidDriver, although I don't think it's related to your particular issue:

```
07-12 09:23:11.300  1151  1327 I am_create_activity: [0,-1289919616,2,io.selendroid.androiddriver/.WebViewActivity,android.intent.action.MAIN,NULL,NULL,872546304]
07-12 09:23:11.310  1151  1438 I am_restart_activity: [0,-1289919616,2,io.selendroid.androiddriver/.WebViewActivity]
07-12 09:23:11.300  1151  1169 W WindowManager: Token{b312a4a0 ActivityRecord{b31d6380 u0 io.selendroid.androiddriver/.WebViewActivity t2}} failed creating starting window
07-12 09:23:11.300  1151  1169 W WindowManager: java.lang.RuntimeException: Binary XML file line #31: You must supply a layout_height attribute.
07-12 09:23:11.300  1151  1169 W WindowManager: 	at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:492)
07-12 09:23:11.300  1151  1169 W WindowManager: 	at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:5949)
07-12 09:23:11.300  1151  1169 W WindowManager: 	at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:6117)
07-12 09:23:11.300  1151  1169 W WindowManager: 	at android.widget.LinearLayout$LayoutParams.<init>(LinearLayout.java:1831)
07-12 09:23:11.300  1151  1169 W WindowManager: 	at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1743)
07-12 09:23:11.300  1151  1169 W WindowManager: 	at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:58)
07-12 09:23:11.300  1151  1169 W WindowManager: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:757)
07-12 09:23:11.300  1151  1169 W WindowManager: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
07-12 09:23:11.300  1151  1169 W WindowManager: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
07-12 09:23:11.300  1151  1169 W WindowManager: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
07-12 09:23:11.300  1151  1169 W WindowManager: 	at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:3022)
07-12 09:23:11.300  1151  1169 W WindowManager: 	at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3085)
07-12 09:23:11.300  1151  1169 W WindowManager: 	at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1678)
07-12 09:23:11.300  1151  1169 W WindowManager: 	at com.android.internal.policy.impl.PhoneWindowManager.addStartingWindow(PhoneWindowManager.java:1653)
07-12 09:23:11.300  1151  1169 W WindowManager: 	at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:7157)
07-12 09:23:11.300  1151  1169 W WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-12 09:23:11.300  1151  1169 W WindowManager: 	at android.os.Looper.loop(Looper.java:136)
07-12 09:23:11.300  1151  1169 W WindowManager: 	at android.os.HandlerThread.run(HandlerThread.java:61)
07-12 09:23:11.530  1944  1944 I am_on_resume_called: [0,io.selendroid.androiddriver.WebViewActivity]
```

You can start to see pouchdb do it's thing in the logs, but all I see is:

```
07-12 09:23:17.750  1944  1944 I chromium: [INFO:CONSOLE(6950)] "The above 404 is totally normal. PouchDB is just detecting if the remote DB exists.", source: http://127.0.0.1:8000/dist/pouchdb.js (6950)```

The Selendroid logs shows lots of tests passing near the end:

```
FINE: return value from selendroid android server: {"failures":[],"passed":24,"failed":0,"browser":"Mozilla/5.0 (Linux; Android 4.4.2; Android SDK built for x86 Build/KK) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36","lastPassed":"Remove doc twice with specified id"}
```

.. however the last call to `return window.results` yields one test passing from what I can tell:

```
FINE: return value from selendroid android server: {"failures":[{"message":"timeout of 100000ms exceeded","title":"Remove doc, no callback","stack":"Error: timeout of 100000ms exceeded\n    at done (http://127.0.0.1:8000/node_modules/mocha/mocha.js:4407:67)\n    at http://127.0.0.1:8000/node_modules/mocha/mocha.js:4428:9\n    at db.changes.complete (http://127.0.0.1:8000/tests/integration/test.basics.js:305:11) ...
```

FTR Sauce doesn't do anything extra/special with Android 4.4 - it's the same as our other emulators. Android 5.0+ is a new runtime (ART vs. Dalvik), so that is probably the single biggest difference between these environments.

**Comment by nolanlawson** [comment]
@filmaj I believe 24 tests is how many are run before it starts to try to use IndexedDB. So I'm guessing that somehow IndexedDB is disabled on that phone, and that's the issue (/hunch).

As for the XML issue, that's a standard Android issue, and the solution (as suggested by the logs) is to add the `layout_height` attribute. I'm kind of surprised Selendroid has such a bug, since that's a pretty fundamental thing. Maybe it's just a red herring in this case?

**Comment by daleharvey** [comment]
We actually run like 60 tests before hitting indexeddb, this is failing way before that, going to do a few runs and see if I can narrow it down to some reproducible test, otherwise I think I will restart on the work you did to get appium / emulators up and running in travis

**Comment by filmaj** [comment]
As a former cordova committer, I can attest that WebViews are a pain in the ass!

Is it a deliberate choice to test in a webview context? Or is that just "what's available"? You could try testing in the Stock Android browser on Sauce, too, from 4.4 onwards. Using capabilities like the following, as an example:

```json
{
    "platformName":"Android",
    "platformVersion":"4.4",
    "browserName":"Browser",
    "appium-version":"1.4"
}
```

**Comment by daleharvey** [comment]
I think the 4.4 upwards was the problem, I think we want to test back to 4.2 at least, but ill give running in the 4.4 browser a shot, cheers

**Comment by daleharvey** [comment]
maybe one day

**Pull request closed without merging**
