### PR TITLE
Added a visual diagram to adapters.html (#5035)

### PR DESCRIPTION
**Pull request by pjhampton**
ping @nolanlawson and @nickcolley

Please let me know if you guys don't like it or the info has outdated since we last chatted. I created the SVG file from draw.io. There is a png to default to if SVG isn't supported by the browser. 

Refs: #5035

### CODE REVIEW

**Comment by nolanlawson** [comment]
This. Is. AWESOME. 💯 

Thank you so much!! Can't wait to have this live on the website. Only a few minor corrections:

- node-websql actually runs in Node, whereas HTTP runs in both browser/node, as does memdown, and fruitdown/localstoragedown run in the browser. Maybe the node/browser distinction isn't so helpful and we should just remove it?
- rather than mention *DOWN as unsupported, I would just go ahead and not mention it at all.
- nitpick: you can put `[skip ci]` in the body of your git commit and then that way the tests won't run (no need to run the tests for doc changes)

**Comment by pjhampton** [comment]
Cool @nolanlawson. And no problem at all. I think I fall into 95% of github contributors and don't read the contributing.md

Anyway, is this what you had in mind? If not, let me know and I can hit up the drawing board again.
Thanks for your help ❤️

**Comment by nolanlawson** [comment]
Looks perfect to me, and I am also very happy that you included the PNG as a fallback (although most browsers support SVG these days, so we're _probably_ okay). This gets a big +1 from me.

**Comment by nolanlawson** [comment]
Thank you very much! Appreciate it a lot. I'll do a release and new publish of the site sometime today.

**Pull request merged**
