### PR TITLE
leveldown upgraded to 6.1.1

### PR DESCRIPTION
**Pull request by rasgo-cc**
This is the same as #8529. Just wanted to see if I can do something regarding passing tests. Locally, all tests pass.

### CODE REVIEW

**Comment by srl295** [comment]
> > Any idea how this could be reproduced locally?
> 
> Have you tried:
> 
> ```shell
> nvm use 14 &&
> CLIENT=selenium:firefox npm run test-webpack
> ```
> 
> ?

For me that produces

```
  1) suite2 test.replication.js-http-http #4094 can't fetch server uuid (HTTP error):

      Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      + expected - actual
```

**Comment by srl295** [comment]
Any ideas on this?

**Comment by alxndrsn** [comment]
> Any ideas on this?

I've updated the branch to the latest `master`.  The error is now:

```

SyntaxError: Unexpected token (36:26)
    at Parser.pp$4.raise (/home/runner/work/pouchdb/pouchdb/node_modules/acorn/dist/acorn.js:2927:15)
    at Parser.pp.unexpected (/home/runner/work/pouchdb/pouchdb/node_modules/acorn/dist/acorn.js:698:10)
    at Parser.pp$3.parseIdent (/home/runner/work/pouchdb/pouchdb/node_modules/acorn/dist/acorn.js:2878:12)
    at Parser.pp$3.parsePropertyName (/home/runner/work/pouchdb/pouchdb/node_modules/acorn/dist/acorn.js:2686:107)
    at Parser.pp$3.parseProperty (/home/runner/work/pouchdb/pouchdb/node_modules/acorn/dist/acorn.js:2613:10)
    at Parser.pp$3.parseObj (/home/runner/work/pouchdb/pouchdb/node_modules/acorn/dist/acorn.js:2567:23)
    at Parser.pp$3.parseExprAtom (/home/runner/work/pouchdb/pouchdb/node_modules/acorn/dist/acorn.js:2302:19)
    at Parser.pp$3.parseExprSubscripts (/home/runner/work/pouchdb/pouchdb/node_modules/acorn/dist/acorn.js:2129:21)
    at Parser.pp$3.parseMaybeUnary (/home/runner/work/pouchdb/pouchdb/node_modules/acorn/dist/acorn.js:2106:19)
    at Parser.pp$3.parseExprOps (/home/runner/work/pouchdb/pouchdb/node_modules/acorn/dist/acorn.js:2041:21)
    at Parser.pp$3.parseMaybeConditional (/home/runner/work/pouchdb/pouchdb/node_modules/acorn/dist/acorn.js:2024:21)
    at Parser.pp$3.parseMaybeAssign (/home/runner/work/pouchdb/pouchdb/node_modules/acorn/dist/acorn.js:1997:21)
    at Parser.pp$3.parseExprList (/home/runner/work/pouchdb/pouchdb/node_modules/acorn/dist/acorn.js:2830:20)
    at Parser.pp$3.parseSubscript (/home/runner/work/pouchdb/pouchdb/node_modules/acorn/dist/acorn.js:2184:27)
    at Parser.pp$3.parseSubscripts (/home/runner/work/pouchdb/pouchdb/node_modules/acorn/dist/acorn.js:2147:26)
    at Parser.pp$3.parseExprSubscripts (/home/runner/work/pouchdb/pouchdb/node_modules/acorn/dist/acorn.js:2132:23) {
  pos: 889,
  loc: Position { line: 36, column: 26 },
  raisedAt: 892
}
```

**Comment by srl295** [comment]
ping?

**Comment by garethbowen** [comment]
Done via https://github.com/pouchdb/pouchdb/pull/8845

**Pull request closed without merging**
