### PR TITLE
(#5251) - Add deprecation notice for async constructor

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by nolanlawson** [comment]
coverage was 99.98 but says it increased. not sure why coveralls failed; happy to merge regardless

**Comment by nolanlawson** [comment]
Oh wait, coverage actually decreased; that's the bug. So we aren't actually testing `new PouchDB(callback)` anywhere

**Comment by daleharvey** [comment]
oh crap yeh I hit this before, should have rebased, during coverage we always go via the `.defaults` constructor, will fix test and merge, cheers

**Comment by daleharvey** [comment]
I rebased against master and its 100%, Should have rebased before but merged and thanks https://github.com/pouchdb/pouchdb/commit/9cda514a3a2f85f65406fe236f8d8828bbcb3acd

**Pull request closed without merging**
