### PR TITLE
(#5154) - Remove db.put(doc, id, rev)

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by nolanlawson** [comment]
Breaking change, but I am +1 on this after 5.4.2 release.

**Comment by daleharvey** [comment]
Are we ready to start landing these?

**Comment by nolanlawson** [comment]
Yup, we can start landing breaking changes anytime. Worst case scenario we
can just cherry pick anyway.

**Comment by daleharvey** [comment]
Awesome thanks

**Pull request merged**
