### PR TITLE
(#2960) - PouchDB itself at PouchDB.com

### PR DESCRIPTION
**Pull request by nolanlawson**
What this looks like in Chrome:

screenshot 2015-02-15 11 44 14

And in Firefox:

screenshot 2015-02-15 11 44 07

### CODE REVIEW

**Comment by nolanlawson** [comment]
The AppCache listeners are to make sure that the output appears after all the Chrome debugging output.

**Comment by calvinmetcalf** [comment]
I made a pull request on your pull request #3541

**Comment by nickcolley** [comment]
@nolanlawson might be worth thinking about doing live examples like you have done with pouchdb-find.

A good place would be the guide, what do you think?

Related: #1991

**Comment by nolanlawson** [comment]
@nickcolley We definitely need some kind of "try pouch" demo. The trouble with the guide would be that I used the same database name for all the examples, so they collide. :/ Just need to go in there and rename all the databases to `'example1'`, `'example2'`, etc. And then figure out a good way to inline the runnable code samples.

**Comment by nolanlawson** [comment]
After @calvinmetcalf's fixes:

screenshot 2015-02-18 08 22 40

**Comment by daleharvey** [comment]
Yeh this isnt a replacement for a full blown try.pouchdb site, but its cute and there arent many reasons not to, +1, cheers

**Comment by daleharvey** [comment]
Merged in https://github.com/pouchdb/pouchdb/commit/f030c96feab5353004aeb37f2563f50dd6655861

**Pull request closed without merging**
