### PR TITLE
Updated link for Felix's Node.js Style Guide

### PR DESCRIPTION
**Pull request by yaronyg**

### CODE REVIEW

**Comment by yaronyg** [comment]
Waiting for a +1 before I commit it.

**Comment by daleharvey** [comment]
Whats the reason for the switch? 

@felixge any reason to prefer one over the other?

**Comment by yaronyg** [comment]
Because the current link says explicitly that it's outdated and one should instead check the second link. So I put in the second link.

**Comment by nolanlawson** [comment]
63a0a10b11b59b3c6bb3c733f50c50585777cf90

**Pull request closed without merging**
