### PR TITLE
Saving of 12kb in payload if site css is minified

### PR DESCRIPTION
**Pull request by robcalcroft**
Added `css-min` to the site build process, small change but saves 12kb.

### CODE REVIEW

**Comment by nickcolley** [comment]
This looks great to me thanks @robcalcroft 

Going to wait on @daleharvey because in the past he had some objections to too many website dependencies in the repo.

**Comment by daleharvey** [comment]
This looks great to me, cant test it right now but happy to 👍 it, thanks :)

**Comment by nickcolley** [comment]
Okay I'll get it tested and merge it in :tada:

**Comment by robcalcroft** [comment]
Just removed the `^` from the version of `css-min`

**Comment by nickcolley** [comment]
2aa654bb96588e7

Thanks a ton :)

If it's okay I'm going to give you a shoutout on Twitter since it's your first PR to PouchDB?

**Comment by robcalcroft** [comment]
Sure!

**Pull request closed without merging**
