### PR TITLE
(#3410) - use pouchdb-upsert

### PR DESCRIPTION
**Pull request by nolanlawson**

### CODE REVIEW

**Comment by daleharvey** [comment]
Failures look genuine

**Comment by nolanlawson** [comment]
that should do it

**Comment by daleharvey** [comment]
Ok cool, splitting this out seems good and I am gonna do a coverage run in a while to see what parts of the code are unused and taking up build space

**Comment by daleharvey** [comment]
Merged in https://github.com/pouchdb/pouchdb/commit/a258a54c6ac6797b12505b41a339e4e8acf465ee

**Pull request closed without merging**
