### PR TITLE
Test multple versions of nodejs

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by daleharvey** [comment]
Cross fingers, hoping these new ones pass but if not will allow_fail the failing ones and start on them

**Comment by daleharvey** [comment]
Hrm not looking good, adding to allowed failures and will start looking into them

**Comment by nolanlawson** [comment]
+1 when green, at least good to know which versions of node fail for us

**Comment by nolanlawson** [comment]
Yikes, we fail on everything but 0.10.

0.11, 0.12, stable, and iojs are all failing. :(

**Comment by nolanlawson** [comment]
c007e336a22856a9b1cf55195f6b28529279b8b5

**Comment by nolanlawson** [comment]
Travis build for those interested: https://travis-ci.org/pouchdb/pouchdb/builds/62616554

**Pull request closed without merging**
