### PR TITLE
WIP - Testing firefox

### PR DESCRIPTION
**Pull request by daleharvey**
Background: #5561 _(Edit by Nolan)_

### CODE REVIEW

**Comment by nolanlawson** [comment]
Maybe it's time to switch to SauceLabs' Firefox? Else I say we file an issue on Travis.

**Comment by nolanlawson** [comment]
I know there's been some changes with the Marionette driver, trying firefox 46 - 48...

**Comment by nolanlawson** [comment]
Yeah every single build is stalling out when Selenium tries to connect. I can't find any combination that works. 😕

**Comment by daleharvey** [comment]
Any chance its related to https://github.com/vvo/selenium-standalone/pull/204 ?

**Comment by nolanlawson** [comment]
No, that was unrelated. I just did that because I noticed 0.9.0 was out of date.

**Comment by nolanlawson** [comment]
Welp, Saucelabs is green; I guess that settles it unless Travis support gets back to us soon? I'd prefer if we nailed down the Firefox version, though.

**Comment by Lyoness** [comment]
Hello! just deployed this runtime fix https://github.com/travis-ci/travis-build/pull/823 testing on your matrix now.

**Pull request closed without merging**
