### PR TITLE
(#2513) - Add option to configure withCredentials

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by daleharvey** [comment]
So testing this would require a fairly large chunk of work as the option doesnt make any other effect than to control how the browser handles requests, we already have tests to ensure the options get passed through to the requests so I skipped it.

I know we lean towards `snake_case`, but that is for consistency with CouchDB, in this case I think the only sensible option is to be consistent with the property it is setting `xhr.withCredentials`

**Comment by nolanlawson** [comment]
Hm, how about just `options.credentials`? I just get a bit nitpicky about this, would prefer to keep consistent case. :P

**Comment by daleharvey** [comment]
I am usually fine with being nitpicky about consistency, but this is directly setting the `withCredentials` parameter, calling it anything else is asking for users to be confused, its what they will be searching for.

**Comment by nolanlawson** [comment]
Fair enough, we do a similar thing for the SQLite plugin due to its superReminiscentOfJavaOptionNames, so it makes sense here too. +1

**Comment by nolanlawson** [comment]
efe5dd8aa645e349a46a8e293703310c8da06ea2

**Pull request closed without merging**
