### PR TITLE
(#3480) - add myself to contributors list

### PR DESCRIPTION
**Pull request by nolanlawson**
Put myself at number two because apparently I've surpassed Calvin
by now. Your move, Cal. :)

### CODE REVIEW

**Comment by nickcolley** [comment]
:+1:

**Comment by daleharvey** [comment]
This isnt the contributors list, I refer to https://github.com/pouchdb/pouchdb/graphs/contributors when I mention a contributors list. I found a lot of people who wanted to contribute to an OSS project said it would be easier if they had a way to privately contact a mentor type person, someone who was familiar with the project

I dont think its been particularly used, but probably worth keeping around and expect you would be happy being on that list anyway :) +1

**Comment by nolanlawson** [comment]
yeah it's more like "if this guy's asleep, talk to this other guy" :)

**Comment by daleharvey** [comment]
Merged in https://github.com/pouchdb/pouchdb/commit/4bd0168436446738830aaa3d77162c72be21808e, cheers

**Pull request closed without merging**
