### PR TITLE
Suggested copyedits to blog post on filtered replication

### PR DESCRIPTION
**Pull request by nolanlawson**
Suggested copyedits for https://github.com/pouchdb/pouchdb/pull/3696

### CODE REVIEW

**Comment by sphaso** [comment]
Thanks a lot for the edits! It flows much more nicely.

**Comment by daleharvey** [comment]
Huge :+1: thanks a lot Giovanni, getting more blog posts to help people is a huge help

**Comment by sphaso** [comment]
My pleasure! One doubt: will next version be 3.3.0 even if today's version is 3.3.1?

**Comment by daleharvey** [comment]
Heh no likely a 3.4.0 I think

**Comment by sphaso** [comment]
Oh ok, so is there a typo in the post?

> To reproduce the examples you’ll need PouchDB v3.3.0, which contains some bugfixes for filtered replication.

I guess you'll need v.3.4.0?

**Comment by nolanlawson** [comment]
yeah that was a typo, I'll fix

**Comment by daleharvey** [comment]
Merged in https://github.com/pouchdb/pouchdb/commit/aeac031151c3f957c38da95aa6b719c445d33db2, thanks so much for the blog post and the copy edits :)

**Pull request closed without merging**
